import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { globToRegExp, loadGeneratedFilePolicy } from "../src/infrastructure/generated-file-policy.js";
import { PolicyEnforcedReadOnlyToolRegistry } from "../src/infrastructure/policy-enforced-read-only-tool-registry.js";
import { createRepositoryWriteTools, registerRepositoryWriteTools } from "../src/infrastructure/repository-write-tools.js";
import { SafeRepositoryFileEditor } from "../src/infrastructure/safe-repository-file-editor.js";

async function repository(t: test.TestContext, files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "atlas-generated-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  for (const [path, content] of Object.entries(files)) {
    await mkdir(join(root, path, ".."), { recursive: true });
    await writeFile(join(root, path), content);
  }
  return root;
}

function tools(root: string): PolicyEnforcedReadOnlyToolRegistry {
  const registry = new PolicyEnforcedReadOnlyToolRegistry({ policy: { defaultDecision: "allow", rules: [] } });
  registerRepositoryWriteTools(registry, createRepositoryWriteTools({ repositoryId: "r", repositoryRoot: root }, { editor: new SafeRepositoryFileEditor() }));
  return registry;
}

function run(registry: PolicyEnforcedReadOnlyToolRegistry, name: string, input: unknown) {
  return registry.execute({ name, input, scope: { kind: "repository", repositoryId: "r" }, context: { repositoryId: "r" } });
}

test("classifies lockfiles, installed dependencies, vendored copies and generator output", async (t) => {
  const root = await repository(t, {
    "package-lock.json": "{}\n",
    "src/api.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
    "src/schema.ts": "/**\n * @generated by relay-compiler\n */\nexport {};\n",
    "src/hand.ts": "// Please do not edit this list without asking the owners.\nexport {};\n",
    "src/late.ts": "1\n2\n3\n4\n5\n6\n// @generated\n",
  });
  const policy = await loadGeneratedFilePolicy(root);
  assert.equal((await policy.classify("package-lock.json"))?.kind, "lockfile");
  assert.match((await policy.classify("package-lock.json"))!.reason, /npm install/);
  assert.equal((await policy.classify("apps/web/node_modules/x/index.js"))?.kind, "dependency");
  assert.equal((await policy.classify("vendor/github.com/x/y.go"))?.kind, "vendored");
  assert.equal((await policy.classify("src/api.pb.go"))?.kind, "generated");
  assert.equal((await policy.classify("src/schema.ts"))?.kind, "generated");
  assert.equal(await policy.classify("src/hand.ts"), null, "a comment that merely says do not edit is not a generator marker");
  assert.equal(await policy.classify("src/late.ts"), null, "markers are only read from the top of a file");
  assert.equal(await policy.classify("src/new.ts"), null);
  assert.equal(await policy.classify("docs/vendor.md"), null, "only directories named vendor count");
});

test(".gitattributes marks files and clears the defaults, later lines winning", async (t) => {
  const root = await repository(t, {
    ".gitattributes": [
      "# comment",
      "*.snap linguist-generated",
      "dist/** linguist-generated=true",
      "vendor/ours/** -linguist-vendored",
      "package-lock.json linguist-generated=false",
      "*.snap -linguist-generated",
      "src/*.snap linguist-generated",
    ].join("\n"),
    "package-lock.json": "{}\n",
  });
  const policy = await loadGeneratedFilePolicy(root);
  assert.equal((await policy.classify("dist/app.js"))?.kind, "generated");
  assert.equal(await policy.classify("lib/dist/app.js"), null, "a pattern with a slash is anchored to the root");
  assert.equal(await policy.classify("vendor/ours/patch.go"), null);
  assert.equal((await policy.classify("vendor/theirs/lib.go"))?.kind, "vendored");
  assert.equal(await policy.classify("package-lock.json"), null);
  assert.equal(await policy.classify("tests/a.snap"), null);
  assert.equal((await policy.classify("src/a.snap"))?.kind, "generated");
});

test("glob patterns follow gitattributes matching", () => {
  assert.ok(globToRegExp("*.pb.go").test("a/b/x.pb.go"));
  assert.ok(!globToRegExp("*.pb.go").test("x.pb.gox"));
  assert.ok(globToRegExp("/gen/*.ts").test("gen/a.ts"));
  assert.ok(!globToRegExp("/gen/*.ts").test("gen/sub/a.ts"));
  assert.ok(globToRegExp("**/gen/*.ts").test("a/b/gen/x.ts"));
  assert.ok(globToRegExp("**/gen/*.ts").test("gen/x.ts"));
  assert.ok(globToRegExp("build/").test("pkg/build/out.js"));
  assert.ok(!globToRegExp("a?c").test("a/c"));
});

test("the write tools refuse a generated-file edit once, then accept a confirmed one", async (t) => {
  const generated = "// Code generated by stringer. DO NOT EDIT.\npackage x\n";
  const root = await repository(t, { "gen.go": generated });
  const registry = tools(root);

  const refused = await run(registry, "repository.propose_file_edit", { path: "gen.go", content: "package x\n" });
  assert.equal(refused.status, "failed");
  assert.match(refused.status === "failed" ? refused.message : "", /gen\.go says it is generated .*allowGenerated: true/s);
  assert.equal(await readFile(join(root, "gen.go"), "utf8"), generated, "nothing was written");

  const confirmed = await run(registry, "repository.propose_file_edit", { path: "gen.go", content: "package x\n", allowGenerated: true });
  assert.equal(confirmed.status, "completed");
  assert.equal(await readFile(join(root, "gen.go"), "utf8"), "package x\n");
});

test("a change set names every protected path and applies nothing until each is confirmed", async (t) => {
  const root = await repository(t, { "package.json": "{}\n", "package-lock.json": "{}\n", "vendor/lib.js": "old\n" });
  const registry = tools(root);
  const edits = [
    { operation: "update", path: "package.json", content: "{\"a\":1}\n" },
    { operation: "update", path: "package-lock.json", content: "{\"a\":1}\n" },
    { operation: "delete", path: "vendor/lib.js" },
  ];

  const refused = await run(registry, "repository.propose_change_set", { edits });
  assert.equal(refused.status, "failed");
  const message = refused.status === "failed" ? refused.message : "";
  assert.match(message, /package-lock\.json is a lockfile/);
  assert.match(message, /vendor\/lib\.js is inside vendor\//);
  assert.match(message, /on those edits/);
  assert.equal(await readFile(join(root, "package.json"), "utf8"), "{}\n", "the unprotected edit did not land either");

  const partly = await run(registry, "repository.propose_change_set", { edits: [edits[0], { ...edits[1], allowGenerated: true }, edits[2]] });
  assert.equal(partly.status, "failed", "confirming one edit does not confirm another");
  assert.doesNotMatch(partly.status === "failed" ? partly.message : "", /lockfile/);

  const confirmed = await run(registry, "repository.propose_change_set", {
    edits: [edits[0], { ...edits[1], allowGenerated: true }, { ...edits[2], allowGenerated: true }],
  });
  assert.equal(confirmed.status, "completed");
  assert.equal(await readFile(join(root, "package-lock.json"), "utf8"), "{\"a\":1}\n");
});

test("a rename into a vendored directory is refused, and a symlinked file is never read for markers", async (t) => {
  const root = await repository(t, { "src/a.js": "a\n" });
  const outside = await repository(t, { "secret.txt": "@generated TOP-SECRET-VALUE\n" });
  await symlink(join(outside, "secret.txt"), join(root, "src/link.js"));
  const registry = tools(root);

  const rename = await run(registry, "repository.propose_change_set", { edits: [{ operation: "rename", path: "src/a.js", toPath: "third_party/a.js" }] });
  assert.equal(rename.status, "failed");

  const linked = await run(registry, "repository.propose_file_edit", { path: "src/link.js", content: "x\n" });
  assert.equal(linked.status, "failed");
  assert.doesNotMatch(linked.status === "failed" ? linked.message : "", /TOP-SECRET-VALUE/);
});

test("allowGenerated must be a boolean", async (t) => {
  const root = await repository(t, {});
  const result = await run(tools(root), "repository.propose_file_edit", { path: "a.ts", content: "", allowGenerated: "yes" });
  assert.equal(result.status, "failed");
  assert.match(result.status === "failed" ? result.message : "", /allowGenerated must be a boolean/u);
});
