import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { promisify } from "node:util";
import { readJson, sendJson } from "./http.mjs";

// Generated by Atlas Genesis. Email and password sign-in with server-side
// sessions, stored in the app's SQLite file.
//
// - Passwords are hashed with scrypt and a random salt; only the hash is kept.
// - A session is a random token in an HttpOnly, SameSite=Lax cookie (and, for
//   API clients, an "Authorization: Bearer" header); only its SHA-256 is stored.
// - Sign-up is "first-user" by default: the first account becomes the owner
//   and later accounts are added by the owner. "open" lets anyone sign up.
// - Repeated failed sign-ins for an address are slowed down.
//
// Routes (all under /api/auth/): POST signup, POST login, POST logout,
// GET me ({ user } or { user: null, signupOpen }), DELETE me (delete your own account), POST users (owner only: add
// an account).

const scrypt = promisify(scryptCallback);
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/u;
const COOKIE = "sid";
const SESSION_DAYS = 14;
const MIN_PASSWORD = 8;
const MAX_PASSWORD = 256;
const FAILURE_LIMIT = 10;
const FAILURE_WINDOW_MS = 15 * 60 * 1000;
const KEY_LENGTH = 32;

const fail = (status, message) => Object.assign(new Error(message), { status });
const digest = (token) => createHash("sha256").update(token).digest("hex");

export async function hashPassword(password, salt = randomBytes(16)) {
  const key = await scrypt(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString("base64")}$${key.toString("base64")}`;
}

export async function verifyPassword(password, stored) {
  const [scheme, saltText, keyText] = String(stored).split("$");
  if (scheme !== "scrypt" || !saltText || !keyText) return false;
  const expected = Buffer.from(keyText, "base64");
  const actual = await scrypt(password, Buffer.from(saltText, "base64"), expected.length);
  return timingSafeEqual(actual, expected);
}

function checkCredentials(input) {
  const email = typeof input.email === "string" ? input.email.trim().toLowerCase() : "";
  const password = typeof input.password === "string" ? input.password : "";
  const errors = {};
  if (!EMAIL.test(email) || email.length > 200) errors.email = "Enter a valid email address.";
  if (password.length < MIN_PASSWORD) errors.password = `Use at least ${MIN_PASSWORD} characters.`;
  else if (password.length > MAX_PASSWORD) errors.password = "That password is too long.";
  if (Object.keys(errors).length) throw Object.assign(fail(400, Object.values(errors)[0]), { errors });
  return { email, password };
}

function cookieValue(request, name) {
  for (const part of String(request.headers.cookie ?? "").split(";")) {
    const [key, ...rest] = part.trim().split("=");
    if (key === name) return rest.join("=");
  }
  return null;
}

export class Auth {
  #db;
  #failures = new Map();
  #now;
  #dummyHash = null;

  /**
   * `bearer: true` also returns the session token in the response body, for
   * API clients that send "Authorization: Bearer". Browser apps leave it off
   * so the token stays in the HttpOnly cookie, out of reach of page scripts.
   *
   * @param {{ filename?: string, signup?: "first-user" | "open", secureCookies?: boolean, bearer?: boolean, now?: () => number }} options
   */
  constructor({ filename = ":memory:", signup = "first-user", secureCookies = false, bearer = false, now = Date.now } = {}) {
    this.bearer = bearer;
    if (filename !== ":memory:") mkdirSync(dirname(filename), { recursive: true });
    this.signup = signup === "open" ? "open" : "first-user";
    this.secureCookies = secureCookies;
    this.#now = now;
    this.#db = new DatabaseSync(filename);
    this.#db.exec(`
      PRAGMA journal_mode = WAL;
      CREATE TABLE IF NOT EXISTS auth_users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'member',
        created_at TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS auth_sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
        expires_at INTEGER NOT NULL
      );
    `);
  }

  close() { this.#db.close(); }

  userCount() { return this.#db.prepare("SELECT COUNT(*) AS n FROM auth_users").get().n; }

  signupOpen() { return this.signup === "open" || this.userCount() === 0; }

  /**
   * Adds an account. `role: "auto"` makes the first account the owner; with
   * `signingUp`, sign-up must still be open once the password is hashed, so
   * two people racing to be first cannot both become owners.
   */
  async createUser(input, { role = "member", signingUp = false } = {}) {
    const { email, password } = checkCredentials(input);
    const hash = await hashPassword(password);
    // Synchronous from here on: nothing else runs between the checks and the insert.
    if (signingUp && !this.signupOpen()) throw fail(403, "Sign-up is closed. Ask the owner to add your account.");
    if (this.#db.prepare("SELECT 1 FROM auth_users WHERE email = ?").get(email)) {
      throw Object.assign(fail(409, "An account with that email already exists."), { errors: { email: "An account with that email already exists." } });
    }
    if (role === "auto") role = this.userCount() === 0 ? "owner" : "member";
    const created = new Date(this.#now()).toISOString();
    const result = this.#db.prepare("INSERT INTO auth_users (email, password_hash, role, created_at) VALUES (?, ?, ?, ?)").run(email, hash, role, created);
    return { id: Number(result.lastInsertRowid), email, role, createdAt: created };
  }

  /** Returns the user for valid credentials, or null. Takes the same time whether or not the address exists. */
  async verify(input) {
    const email = typeof input.email === "string" ? input.email.trim().toLowerCase() : "";
    const password = typeof input.password === "string" ? input.password.slice(0, MAX_PASSWORD) : "";
    const key = email;
    const now = this.#now();
    const recent = (this.#failures.get(key) ?? []).filter((at) => now - at < FAILURE_WINDOW_MS);
    if (recent.length >= FAILURE_LIMIT) throw fail(429, "Too many sign-in attempts. Wait a few minutes and try again.");
    const row = this.#db.prepare("SELECT id, email, role, password_hash, created_at FROM auth_users WHERE email = ?").get(email);
    this.#dummyHash ??= await hashPassword("atlas-timing-equaliser");
    const ok = await verifyPassword(password, row?.password_hash ?? this.#dummyHash);
    if (!row || !ok) {
      recent.push(now);
      this.#failures.delete(key);
      this.#failures.set(key, recent);
      // Bounded: the oldest addresses go first, so memory cannot grow without limit.
      while (this.#failures.size > 10_000) this.#failures.delete(this.#failures.keys().next().value);
      return null;
    }
    this.#failures.delete(key);
    return { id: row.id, email: row.email, role: row.role, createdAt: row.created_at };
  }

  /** Deletes an account and its sessions. The owner goes last: never while other accounts depend on them. */
  deleteUser(userId) {
    const row = this.#db.prepare("SELECT role FROM auth_users WHERE id = ?").get(userId);
    if (!row) return false;
    if (row.role === "owner" && this.userCount() > 1) throw fail(409, "The owner cannot delete their account while other accounts exist.");
    this.#db.prepare("DELETE FROM auth_sessions WHERE user_id = ?").run(userId);
    this.#db.prepare("DELETE FROM auth_users WHERE id = ?").run(userId);
    return true;
  }

  startSession(userId) {
    const token = randomBytes(32).toString("base64url");
    const expires = this.#now() + SESSION_DAYS * 24 * 60 * 60 * 1000;
    this.#db.prepare("INSERT INTO auth_sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)").run(digest(token), userId, expires);
    return { token, expires };
  }

  endSession(token) {
    if (token) this.#db.prepare("DELETE FROM auth_sessions WHERE token_hash = ?").run(digest(token));
  }

  /** Removes expired sessions; returns how many. Run by the "purge-expired-sessions" job. */
  purgeExpired() {
    return Number(this.#db.prepare("DELETE FROM auth_sessions WHERE expires_at <= ?").run(this.#now()).changes);
  }

  tokenFrom(request) {
    const header = String(request.headers.authorization ?? "");
    if (this.bearer && header.startsWith("Bearer ")) return header.slice(7).trim() || null;
    return cookieValue(request, COOKIE);
  }

  /** The signed-in user for a request, or null. */
  userFrom(request) {
    const token = this.tokenFrom(request);
    if (!token || token.length > 200) return null;
    const row = this.#db.prepare(`
      SELECT u.id, u.email, u.role, u.created_at, s.expires_at FROM auth_sessions s JOIN auth_users u ON u.id = s.user_id WHERE s.token_hash = ?
    `).get(digest(token));
    if (!row) return null;
    if (row.expires_at <= this.#now()) { this.endSession(token); return null; }
    return { id: row.id, email: row.email, role: row.role, createdAt: row.created_at };
  }

  #cookie(token, maxAgeSeconds) {
    return `${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAgeSeconds}${this.secureCookies ? "; Secure" : ""}`;
  }

  async #signIn(response, user, status) {
    const session = this.startSession(user.id);
    response.setHeader("set-cookie", this.#cookie(session.token, SESSION_DAYS * 24 * 60 * 60));
    return sendJson(response, status, { user, ...(this.bearer ? { token: session.token } : {}), expiresAt: new Date(session.expires).toISOString() });
  }

  /** Handles /api/auth/*; returns false for any other path. */
  async handle(request, response, pathname) {
    if (!pathname.startsWith("/api/auth/")) return false;
    const action = pathname.slice("/api/auth/".length);
    if (action === "me" && request.method === "GET") {
      // 200 either way, so a signed-out page load logs no error; `user` is null when signed out.
      const user = this.userFrom(request);
      return sendJson(response, 200, { user, signupOpen: user ? false : this.signupOpen() });
    }
    if (action === "me" && request.method === "DELETE") {
      const user = this.userFrom(request);
      if (!user) throw fail(401, "Sign in to continue.");
      this.deleteUser(user.id);
      response.setHeader("set-cookie", this.#cookie("", 0));
      return sendJson(response, 200, { deleted: true });
    }
    if (request.method !== "POST") return sendJson(response, 405, { error: "Method not allowed." });
    if (action === "signup") {
      if (!this.signupOpen()) throw fail(403, "Sign-up is closed. Ask the owner to add your account.");
      const user = await this.createUser(await readJson(request), { role: "auto", signingUp: true });
      return this.#signIn(response, user, 201);
    }
    if (action === "login") {
      const user = await this.verify(await readJson(request));
      if (!user) throw fail(401, "That email and password do not match an account.");
      return this.#signIn(response, user, 200);
    }
    if (action === "logout") {
      this.endSession(this.tokenFrom(request));
      response.setHeader("set-cookie", this.#cookie("", 0));
      return sendJson(response, 200, { signedOut: true });
    }
    if (action === "users") {
      const owner = this.userFrom(request);
      if (!owner) throw fail(401, "Sign in to continue.");
      if (owner.role !== "owner") throw fail(403, "Only the owner can add accounts.");
      return sendJson(response, 201, { user: await this.createUser(await readJson(request)) });
    }
    return sendJson(response, 404, { error: "Not found." });
  }
}

/**
 * Rejects state-changing requests sent from another site. Browsers attach an
 * Origin header to cross-site requests; a mismatch with Host is refused.
 */
export function sameOrigin(request) {
  if (["GET", "HEAD", "OPTIONS"].includes(request.method)) return true;
  const origin = request.headers.origin;
  if (!origin) return true;
  try { return new URL(origin).host === request.headers.host; } catch { return false; }
}
