import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { Auth, sameOrigin } from "./auth.mjs";
import { FileStore } from "./files.mjs";
import { sendJson } from "./http.mjs";
import { createScheduler } from "./jobs.mjs";
import { Secrets } from "./secrets.mjs";

// Generated by Atlas Genesis. Puts the app's backend building blocks together
// from app.config.json: sign-in (auth), file storage (files), secrets and
// scheduled jobs, and answers their /api routes.
//
// server.mjs calls `backend.route(request, response, url)` first for every
// /api request. It refuses cross-site writes, enforces sign-in when
// config.auth.required is true (except for the routes `isPublic` allows),
// and handles /api/auth, /api/files, /api/secrets and /api/jobs. Anything
// else comes back as { handled: false, user } for the app's own routes.

export function createBackend({
  config,
  dataFile,
  filesDir = dataFile === ":memory:" ? null : join(dirname(dataFile), "files"),
  secretsFile,
  env = process.env,
  bearer = false,
  jobs = {},
  isPublic = () => false,
}) {
  const authRequired = Boolean(config.auth?.required);
  const auth = new Auth({ filename: dataFile, signup: config.auth?.signup, secureCookies: env.COOKIE_SECURE === "1", bearer });
  const temporaryFiles = config.files?.enabled === false || filesDir ? null : mkdtempSync(join(tmpdir(), "app-files-"));
  const files = config.files?.enabled === false ? null : new FileStore({ dir: filesDir ?? temporaryFiles, filename: dataFile, maxBytes: config.files?.maxBytes });
  const secrets = new Secrets({ file: secretsFile, declared: config.secrets ?? [], env });
  const scheduler = createScheduler({
    schedule: config.jobs ?? [],
    jobs: { "purge-expired-sessions": () => ({ removed: auth.purgeExpired() }), ...jobs },
  });
  const always = new Set(["health", "config", "auth"]);

  async function route(request, response, url) {
    if (!sameOrigin(request)) {
      sendJson(response, 403, { error: "Cross-site requests are not allowed." });
      return { handled: true, user: null };
    }
    const [, , slug, id, extra] = url.pathname.split("/");
    const user = auth.userFrom(request);
    if (authRequired && !user && !always.has(slug) && !isPublic(request, slug, id)) {
      sendJson(response, 401, { error: "Sign in to continue.", signupOpen: auth.signupOpen() });
      return { handled: true, user };
    }
    if (slug === "auth") { await auth.handle(request, response, url.pathname); return { handled: true, user }; }
    if (slug === "files" && files) { await files.handle(request, response, url.pathname, user); return { handled: true, user }; }
    if (slug === "secrets" || slug === "jobs") {
      if (authRequired && user.role !== "owner") sendJson(response, 403, { error: "Only the owner can see this." });
      else if (slug === "secrets" && !id && request.method === "GET") sendJson(response, 200, { secrets: secrets.status() });
      else if (slug === "jobs" && !id && request.method === "GET") sendJson(response, 200, { jobs: scheduler.status() });
      else if (slug === "jobs" && id && extra === "run" && request.method === "POST") sendJson(response, 200, { run: await scheduler.runNow(id) });
      else sendJson(response, 404, { error: "Not found." });
      return { handled: true, user };
    }
    return { handled: false, user };
  }

  return {
    auth, files, secrets, scheduler, route,
    close() {
      scheduler.stop();
      auth.close();
      files?.close();
      if (temporaryFiles) rmSync(temporaryFiles, { recursive: true, force: true });
    },
  };
}
