import { createHash, randomBytes } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { secure, sendJson } from "./http.mjs";

// Generated by Atlas Genesis. File uploads kept on disk next to the app's
// data, with their details in SQLite.
//
// - Only the types in ALLOWED are accepted, and the file's first bytes must
//   match the type it claims (a script renamed to .png is refused).
// - Each upload has a size limit; files are stored under random names, never
//   the uploaded name, so a name cannot reach outside the folder.
// - Downloads are sent with nosniff and a sandboxing CSP; anything that is
//   not an image is sent as an attachment rather than shown in the page.
//
// Routes: POST /api/files (raw body; headers content-type and x-file-name),
// GET /api/files, GET /api/files/:id, DELETE /api/files/:id.

export const DEFAULT_MAX_BYTES = 10 * 1024 * 1024;

const ALLOWED = {
  "image/png": (b) => b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
  "image/jpeg": (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff,
  "image/gif": (b) => /^GIF8[79]a/u.test(b.subarray(0, 6).toString("latin1")),
  "image/webp": (b) => b.subarray(0, 4).toString("latin1") === "RIFF" && b.subarray(8, 12).toString("latin1") === "WEBP",
  "application/pdf": (b) => b.subarray(0, 5).toString("latin1") === "%PDF-",
  "text/plain": (b) => isText(b),
  "text/csv": (b) => isText(b),
};

function isText(buffer) {
  if (buffer.includes(0)) return false;
  try { new TextDecoder("utf-8", { fatal: true }).decode(buffer); return true; } catch { return false; }
}

const fail = (status, message) => Object.assign(new Error(message), { status });

function cleanName(raw) {
  let name = "file";
  try { name = decodeURIComponent(String(raw ?? "")); } catch { /* keep default */ }
  name = name.split(/[\\/]/u).at(-1).replace(/[\u0000-\u001f\u007f"]/gu, "").trim().slice(0, 200);
  return name || "file";
}

export class FileStore {
  #db;
  #dir;

  /** @param {{ dir: string, filename?: string, maxBytes?: number }} options */
  constructor({ dir, filename = ":memory:", maxBytes = DEFAULT_MAX_BYTES }) {
    this.#dir = dir;
    this.maxBytes = maxBytes;
    mkdirSync(dir, { recursive: true });
    this.#db = new DatabaseSync(filename);
    this.#db.exec(`
      PRAGMA journal_mode = WAL;
      CREATE TABLE IF NOT EXISTS app_files (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        size INTEGER NOT NULL,
        sha256 TEXT NOT NULL,
        owner_id INTEGER,
        created_at TEXT NOT NULL
      );
    `);
  }

  close() { this.#db.close(); }

  static allowedTypes() { return Object.keys(ALLOWED); }

  save({ name, type, data, ownerId = null }) {
    const kind = String(type ?? "").split(";")[0].trim().toLowerCase();
    if (!ALLOWED[kind]) throw fail(415, `That file type is not accepted. Allowed: ${Object.keys(ALLOWED).join(", ")}.`);
    if (!data.length) throw fail(400, "The file is empty.");
    if (data.length > this.maxBytes) throw fail(413, `Files can be at most ${Math.round(this.maxBytes / 1024 / 1024)} MB.`);
    if (!ALLOWED[kind](data)) throw fail(415, "The file's contents do not match its type.");
    const id = randomBytes(16).toString("hex");
    writeFileSync(join(this.#dir, id), data, { flag: "wx", mode: 0o600 });
    const record = { id, name: cleanName(name), type: kind, size: data.length, sha256: createHash("sha256").update(data).digest("hex"), ownerId, createdAt: new Date().toISOString() };
    this.#db.prepare("INSERT INTO app_files (id, name, type, size, sha256, owner_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)")
      .run(record.id, record.name, record.type, record.size, record.sha256, record.ownerId, record.createdAt);
    return record;
  }

  get(id) {
    if (!/^[0-9a-f]{32}$/u.test(String(id))) return null;
    const row = this.#db.prepare("SELECT * FROM app_files WHERE id = ?").get(id);
    return row ? { id: row.id, name: row.name, type: row.type, size: row.size, sha256: row.sha256, ownerId: row.owner_id, createdAt: row.created_at } : null;
  }

  list() {
    return this.#db.prepare("SELECT id FROM app_files ORDER BY created_at DESC, id LIMIT 500").all().map((row) => this.get(row.id));
  }

  read(id) {
    const file = this.get(id);
    return file ? { ...file, data: readFileSync(join(this.#dir, file.id)) } : null;
  }

  remove(id) {
    const file = this.get(id);
    if (!file) return false;
    this.#db.prepare("DELETE FROM app_files WHERE id = ?").run(file.id);
    rmSync(join(this.#dir, file.id), { force: true });
    return true;
  }

  async #readBody(request) {
    const declared = Number(request.headers["content-length"]);
    if (Number.isFinite(declared) && declared > this.maxBytes) throw fail(413, `Files can be at most ${Math.round(this.maxBytes / 1024 / 1024)} MB.`);
    const chunks = [];
    let size = 0;
    for await (const chunk of request) {
      size += chunk.length;
      if (size > this.maxBytes) throw fail(413, `Files can be at most ${Math.round(this.maxBytes / 1024 / 1024)} MB.`);
      chunks.push(chunk);
    }
    return Buffer.concat(chunks);
  }

  /** Handles /api/files[/:id]; returns false for any other path. `user` is the signed-in user or null. */
  async handle(request, response, pathname, user = null) {
    const match = /^\/api\/files(?:\/([^/]+))?$/u.exec(pathname);
    if (!match) return false;
    const [, id] = match;
    if (!id) {
      if (request.method === "GET") return sendJson(response, 200, { files: this.list(), maxBytes: this.maxBytes, types: FileStore.allowedTypes() });
      if (request.method !== "POST") return sendJson(response, 405, { error: "Method not allowed." });
      const data = await this.#readBody(request);
      return sendJson(response, 201, { file: this.save({ name: request.headers["x-file-name"], type: request.headers["content-type"], data, ownerId: user?.id ?? null }) });
    }
    if (request.method === "DELETE") return this.remove(id) ? sendJson(response, 200, { deleted: true }) : sendJson(response, 404, { error: "Not found." });
    if (request.method !== "GET") return sendJson(response, 405, { error: "Method not allowed." });
    const file = this.read(id);
    if (!file) return sendJson(response, 404, { error: "Not found." });
    secure(response);
    const inline = file.type.startsWith("image/");
    response.writeHead(200, {
      "content-type": file.type,
      "content-length": String(file.size),
      "content-security-policy": "default-src 'none'; sandbox",
      "content-disposition": `${inline ? "inline" : "attachment"}; filename="${file.name.replace(/[^\x20-\x7e]/gu, "_")}"; filename*=UTF-8''${encodeURIComponent(file.name)}`,
      "cache-control": "private, no-store",
    });
    response.end(file.data);
    return true;
  }
}
