import { readFile } from "node:fs/promises";
import { extname, join, normalize, sep } from "node:path";

// Generated by Atlas Genesis. Small HTTP helpers with safe defaults.

export const MAX_BODY_BYTES = 64 * 1024;

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".xml": "application/xml; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

/** Security headers on every response: no inline scripts, no framing, no sniffing. */
export function secure(response) {
  response.setHeader("content-security-policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
  response.setHeader("x-content-type-options", "nosniff");
  response.setHeader("referrer-policy", "no-referrer");
  response.setHeader("x-frame-options", "DENY");
}

export function sendJson(response, status, value) {
  secure(response);
  response.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });
  response.end(JSON.stringify(value));
}

export async function readJson(request) {
  const chunks = [];
  let size = 0;
  for await (const chunk of request) {
    size += chunk.length;
    if (size > MAX_BODY_BYTES) throw Object.assign(new Error("The request is too large."), { status: 413 });
    chunks.push(chunk);
  }
  if (!chunks.length) return {};
  try {
    const value = JSON.parse(Buffer.concat(chunks).toString("utf8"));
    if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("not an object");
    return value;
  } catch {
    throw Object.assign(new Error("The request body must be a JSON object."), { status: 400 });
  }
}

/** Serves a file from `root` only; anything outside it, or missing, falls back to `fallback` (or 404). */
export async function serveStatic(response, root, pathname, { fallback = null } = {}) {
  const decoded = (() => { try { return decodeURIComponent(pathname); } catch { return "/"; } })();
  const relative = normalize(decoded).replace(/^([/\\])+/u, "");
  const target = join(root, relative || "index.html");
  const inside = target === root || target.startsWith(root.endsWith(sep) ? root : root + sep);
  const candidates = inside ? [target, join(target, "index.html"), `${target}.html`] : [];
  if (fallback) candidates.push(join(root, fallback));
  for (const file of candidates) {
    try {
      const body = await readFile(file);
      secure(response);
      response.writeHead(200, { "content-type": TYPES[extname(file)] ?? "application/octet-stream", "cache-control": "no-cache" });
      response.end(body);
      return true;
    } catch { /* next candidate */ }
  }
  sendJson(response, 404, { error: "Not found." });
  return false;
}
