import { nextRun, parseCron } from "./cron.mjs";

// Generated by Atlas Genesis. Scheduled jobs that run inside the app on a
// cron schedule (five fields, local time: "0 9 * * 1-5" is 9:00 on weekdays).
//
// Declare the schedule in app.config.json ("jobs": [{ "name", "schedule" }])
// and the work in server.mjs (the `jobs` passed to createScheduler). A job
// that is still running when its next time comes is skipped, not doubled; a
// failing job is logged and tried again at its next time.

const MAX_WAIT_MS = 60 * 60 * 1000;

export function createScheduler({ schedule = [], jobs = {}, now = () => new Date(), setTimer = setTimeout, clearTimer = clearTimeout, log = console }) {
  const entries = schedule.map((entry) => {
    if (typeof jobs[entry.name] !== "function") throw new Error(`Job "${entry.name}" is scheduled but not defined.`);
    return { name: entry.name, source: entry.schedule, cron: parseCron(entry.schedule), running: false, timer: null, lastRun: null, nextAt: null };
  });
  let started = false;

  async function run(entry, reason) {
    if (entry.running) return { name: entry.name, status: "skipped", reason: "still running" };
    entry.running = true;
    const startedAt = now();
    try {
      const result = await jobs[entry.name]();
      entry.lastRun = { at: startedAt.toISOString(), reason, status: "succeeded", result: result ?? null };
    } catch (error) {
      entry.lastRun = { at: startedAt.toISOString(), reason, status: "failed", error: error instanceof Error ? error.message : String(error) };
      log.error?.(`Job ${entry.name} failed:`, error);
    } finally {
      entry.running = false;
    }
    return { name: entry.name, ...entry.lastRun };
  }

  function arm(entry) {
    if (!started) return;
    const due = nextRun(entry.cron, now());
    entry.nextAt = due ? due.toISOString() : null;
    if (!due) return;
    const wait = Math.max(0, due.getTime() - now().getTime());
    entry.timer = setTimer(async () => {
      entry.timer = null;
      // Long waits are re-measured so a sleeping laptop or clock change cannot run a job early.
      if (wait > MAX_WAIT_MS || now().getTime() < due.getTime()) return arm(entry);
      await run(entry, "schedule");
      arm(entry);
    }, Math.min(wait, MAX_WAIT_MS));
    entry.timer?.unref?.();
  }

  return {
    start() {
      if (started) return;
      started = true;
      for (const entry of entries) arm(entry);
    },
    stop() {
      started = false;
      for (const entry of entries) if (entry.timer) { clearTimer(entry.timer); entry.timer = null; }
    },
    /** Runs a job now, outside its schedule. */
    async runNow(name) {
      const entry = entries.find((candidate) => candidate.name === name);
      if (!entry) throw Object.assign(new Error(`There is no job called "${name}".`), { status: 404 });
      return run(entry, "manual");
    },
    status() {
      return entries.map(({ name, source, running, lastRun, nextAt }) => ({ name, schedule: source, running, lastRun, nextAt }));
    },
  };
}
