import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

// Generated by Atlas Genesis. The app's secrets (API keys, signing keys),
// kept out of the code and never sent to the browser.
//
// A secret comes from the environment variable of the same name if it is set,
// otherwise from data/secrets.json (written with owner-only permissions and
// ignored by git). Set one with:
//
//   node scripts/secret.mjs set STRIPE_SECRET_KEY      (reads the value from stdin)
//
// Code reads a value with secrets.get(NAME) on the server only. status() lists
// which declared secrets are configured, without their values; that is all
// any API route may return.

const NAME = /^[A-Z][A-Z0-9_]{0,63}$/u;

export class SecretError extends Error {
  constructor(message) {
    super(message);
    this.name = "SecretError";
    this.status = 500;
  }
}

export class Secrets {
  #file;
  #env;

  /** @param {{ file: string, declared?: string[], env?: Record<string, string | undefined> }} options */
  constructor({ file, declared = [], env = process.env }) {
    this.#file = file;
    this.#env = env;
    this.declared = declared.filter((name) => NAME.test(name));
  }

  #stored() {
    if (!existsSync(this.#file)) return {};
    const value = JSON.parse(readFileSync(this.#file, "utf8"));
    return value && typeof value === "object" && !Array.isArray(value) ? value : {};
  }

  has(name) {
    return Boolean(this.#env[name] || this.#stored()[name]);
  }

  /** The value, or a clear error naming the secret (never its value) when it is missing. */
  get(name) {
    if (!NAME.test(name)) throw new SecretError(`"${name}" is not a valid secret name (use UPPER_CASE).`);
    const value = this.#env[name] || this.#stored()[name];
    if (!value) throw new SecretError(`The secret ${name} is not set. Run: node scripts/secret.mjs set ${name}`);
    return value;
  }

  set(name, value) {
    if (!NAME.test(name)) throw new SecretError(`"${name}" is not a valid secret name (use UPPER_CASE).`);
    if (typeof value !== "string" || !value.trim()) throw new SecretError(`The value for ${name} is empty.`);
    const next = { ...this.#stored(), [name]: value.trim() };
    mkdirSync(dirname(this.#file), { recursive: true });
    const temporary = `${this.#file}.tmp`;
    writeFileSync(temporary, `${JSON.stringify(next, null, 2)}\n`, { mode: 0o600 });
    renameSync(temporary, this.#file);
    try { chmodSync(this.#file, 0o600); } catch { /* not supported on every file system */ }
  }

  remove(name) {
    const stored = this.#stored();
    if (!(name in stored)) return false;
    delete stored[name];
    writeFileSync(this.#file, `${JSON.stringify(stored, null, 2)}\n`, { mode: 0o600 });
    return true;
  }

  /** Which secrets are configured and where from; never the values. */
  status() {
    const stored = this.#stored();
    const names = [...new Set([...this.declared, ...Object.keys(stored).filter((name) => NAME.test(name))])].sort();
    return names.map((name) => ({ name, declared: this.declared.includes(name), configured: Boolean(this.#env[name] || stored[name]), source: this.#env[name] ? "environment" : stored[name] ? "file" : null }));
  }
}
