import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";

// Generated by Atlas Genesis. Stores the record types in app.config.json in a
// local SQLite file, with validation from each field's type.

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/u;
const DATE = /^\d{4}-\d{2}-\d{2}$/u;
const TIME = /^([01]\d|2[0-3]):[0-5]\d$/u;
const MAX_TEXT = 2000;

export class ValidationError extends Error {
  constructor(errors) {
    super(Object.values(errors)[0] ?? "Invalid input.");
    this.name = "ValidationError";
    this.status = 400;
    this.errors = errors;
  }
}

/** Checks one record against its fields; returns the cleaned record or throws ValidationError. */
export function validate(entity, input, { partial = false } = {}) {
  const errors = {};
  const clean = {};
  for (const field of entity.fields) {
    const present = Object.hasOwn(input, field.key);
    if (partial && !present) continue;
    let value = input[field.key];
    if (value === undefined || value === null) value = "";
    if (typeof value === "number" && field.type === "number") value = String(value);
    if (typeof value !== "string") { errors[field.key] = `${field.label} must be text.`; continue; }
    value = value.trim();
    if (!value) {
      if (field.required) errors[field.key] = `${field.label} is required.`;
      else clean[field.key] = field.type === "select" && field.options?.length && !partial ? field.options[0] : "";
      continue;
    }
    if (value.length > MAX_TEXT) { errors[field.key] = `${field.label} is too long.`; continue; }
    if (field.type === "email" && !EMAIL.test(value)) errors[field.key] = `${field.label} must be an email address.`;
    else if (field.type === "number" && !Number.isFinite(Number(value))) errors[field.key] = `${field.label} must be a number.`;
    else if (field.type === "date" && (!DATE.test(value) || Number.isNaN(Date.parse(value)))) errors[field.key] = `${field.label} must be a date (YYYY-MM-DD).`;
    else if (field.type === "time" && !TIME.test(value)) errors[field.key] = `${field.label} must be a time (HH:MM).`;
    else if (field.type === "select" && field.options?.length && !field.options.includes(value)) errors[field.key] = `${field.label} must be one of: ${field.options.join(", ")}.`;
    else clean[field.key] = field.type === "number" ? String(Number(value)) : value;
  }
  if (Object.keys(errors).length) throw new ValidationError(errors);
  return clean;
}

export class RecordStore {
  #db;

  constructor(entities, filename = ":memory:") {
    if (filename !== ":memory:") mkdirSync(dirname(filename), { recursive: true });
    this.entities = new Map(entities.map((entity) => [entity.slug, entity]));
    this.#db = new DatabaseSync(filename);
    this.#db.exec("PRAGMA journal_mode = WAL;");
    for (const entity of entities) {
      if (!/^[a-z][a-z0-9_]{0,40}$/u.test(entity.slug)) throw new Error(`Unsafe record type name: ${entity.slug}`);
      this.#db.exec(`CREATE TABLE IF NOT EXISTS ${entity.slug} (id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT NOT NULL, search TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`);
    }
  }

  close() { this.#db.close(); }

  entity(slug) {
    const entity = this.entities.get(slug);
    if (!entity) throw Object.assign(new Error("Unknown record type."), { status: 404 });
    return entity;
  }

  #row(row) {
    return row ? { id: row.id, ...JSON.parse(row.data), createdAt: row.created_at, updatedAt: row.updated_at } : null;
  }

  list(slug, { q = "", limit = 200 } = {}) {
    const entity = this.entity(slug);
    const term = String(q).trim().toLowerCase().slice(0, 100);
    const rows = term
      ? this.#db.prepare(`SELECT * FROM ${entity.slug} WHERE search LIKE ? ESCAPE '\\' ORDER BY id DESC LIMIT ?`).all(`%${term.replace(/[\\%_]/gu, (c) => `\\${c}`)}%`, limit)
      : this.#db.prepare(`SELECT * FROM ${entity.slug} ORDER BY id DESC LIMIT ?`).all(limit);
    return rows.map((row) => this.#row(row));
  }

  get(slug, id) {
    const entity = this.entity(slug);
    return this.#row(this.#db.prepare(`SELECT * FROM ${entity.slug} WHERE id = ?`).get(Number(id)));
  }

  create(slug, input) {
    const entity = this.entity(slug);
    const record = validate(entity, input);
    const now = new Date().toISOString();
    const result = this.#db.prepare(`INSERT INTO ${entity.slug} (data, search, created_at, updated_at) VALUES (?, ?, ?, ?)`)
      .run(JSON.stringify(record), Object.values(record).join(" ").toLowerCase(), now, now);
    return this.get(slug, result.lastInsertRowid);
  }

  update(slug, id, input) {
    const entity = this.entity(slug);
    const current = this.get(slug, id);
    if (!current) return null;
    const changes = validate(entity, input, { partial: true });
    const { id: _id, createdAt, updatedAt, ...data } = current;
    const next = { ...data, ...changes };
    this.#db.prepare(`UPDATE ${entity.slug} SET data = ?, search = ?, updated_at = ? WHERE id = ?`)
      .run(JSON.stringify(next), Object.values(next).join(" ").toLowerCase(), new Date().toISOString(), Number(id));
    return this.get(slug, id);
  }

  remove(slug, id) {
    const entity = this.entity(slug);
    return this.#db.prepare(`DELETE FROM ${entity.slug} WHERE id = ?`).run(Number(id)).changes > 0;
  }

  /** Counts per record type, by status (or stage) when the type has one. */
  stats() {
    const result = {};
    for (const entity of this.entities.values()) {
      const statusField = entity.fields.find((field) => field.type === "select");
      const rows = this.#db.prepare(`SELECT data FROM ${entity.slug}`).all().map((row) => JSON.parse(row.data));
      const byStatus = {};
      if (statusField) for (const option of statusField.options ?? []) byStatus[option] = 0;
      if (statusField) for (const row of rows) byStatus[row[statusField.key]] = (byStatus[row[statusField.key]] ?? 0) + 1;
      result[entity.slug] = { label: entity.plural, count: rows.length, statusField: statusField?.label ?? null, byStatus };
    }
    return result;
  }
}
