// Generated by Atlas Genesis (static-site template). Sends the enquiry form.

const form = document.getElementById("enquiry");
const error = document.getElementById("enquiry-error");
const done = document.getElementById("enquiry-done");

form?.addEventListener("submit", async (event) => {
  event.preventDefault();
  const button = form.querySelector("button[type=submit]");
  const data = Object.fromEntries(new FormData(form).entries());
  error.hidden = true;
  button.disabled = true;
  try {
    const response = await fetch("/api/enquiries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error ?? "The message could not be sent.");
    form.hidden = true;
    done.hidden = false;
  } catch (failure) {
    error.textContent = failure.message;
    error.hidden = false;
  } finally {
    button.disabled = false;
  }
});
