import assert from "node:assert/strict";
import test from "node:test";
import { config, createApp } from "../server.mjs";

// Generated by Atlas Genesis (web-app template). Exercises every record type
// in app.config.json through the real HTTP API.

function sample(entity, suffix = "one") {
  const record = {};
  for (const field of entity.fields) {
    if (field.type === "email") record[field.key] = `${suffix}@example.com`;
    else if (field.type === "tel") record[field.key] = "555-0100";
    else if (field.type === "number") record[field.key] = "42";
    else if (field.type === "date") record[field.key] = "2030-05-01";
    else if (field.type === "time") record[field.key] = "09:30";
    else if (field.type === "select") record[field.key] = field.options.at(-1);
    else record[field.key] = `${field.label} ${suffix}`;
  }
  return record;
}

async function withApp(run) {
  const server = createApp({ dataFile: ":memory:" });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = async (path, options = {}) => {
    const response = await fetch(`${base}${path}`, { ...options, headers: { "content-type": "application/json" } });
    return { status: response.status, headers: response.headers, body: response.headers.get("content-type")?.includes("json") ? await response.json() : await response.text() };
  };
  try { await run(call); } finally { await new Promise((resolve) => server.close(resolve)); }
}

test("the app serves its page with security headers", () => withApp(async (call) => {
  const page = await call("/");
  assert.equal(page.status, 200);
  assert.match(page.body, /<script type="module" src="\/app.js">/u);
  assert.match(page.headers.get("content-security-policy"), /script-src 'self'/u);
  assert.equal(page.headers.get("x-content-type-options"), "nosniff");
  assert.equal((await call("/app.js")).status, 200);
  assert.equal((await call("/api/health")).body.ok, true);
  assert.equal((await call("/api/config")).body.name, config.name);
  assert.equal((await call("/../server.mjs")).body.includes?.("createServer"), false, "files outside public are never served");
}));

for (const entity of config.entities) {
  test(`${entity.plural}: create, list, search, update and delete`, () => withApp(async (call) => {
    const created = await call(`/api/${entity.slug}`, { method: "POST", body: JSON.stringify(sample(entity, "alpha")) });
    assert.equal(created.status, 201, JSON.stringify(created.body));
    await call(`/api/${entity.slug}`, { method: "POST", body: JSON.stringify(sample(entity, "beta")) });
    const all = await call(`/api/${entity.slug}`);
    assert.equal(all.body.records.length, 2);
    const searchField = entity.fields.find((field) => ["text", "email", "textarea"].includes(field.type));
    if (searchField) {
      const found = await call(`/api/${entity.slug}?q=alpha`);
      assert.equal(found.body.records.length, 1, "search finds only the matching record");
      assert.equal(found.body.records[0].id, created.body.record.id);
    }
    const first = entity.fields[0];
    const updated = await call(`/api/${entity.slug}/${created.body.record.id}`, { method: "PATCH", body: JSON.stringify({ [first.key]: first.type === "email" ? "changed@example.com" : first.type === "number" ? "7" : first.type === "select" ? first.options[0] : "Changed" }) });
    assert.equal(updated.status, 200, JSON.stringify(updated.body));
    const statusField = entity.fields.find((field) => field.type === "select");
    if (statusField) {
      const moved = await call(`/api/${entity.slug}/${created.body.record.id}`, { method: "PATCH", body: JSON.stringify({ [statusField.key]: statusField.options[0] }) });
      assert.equal(moved.body.record[statusField.key], statusField.options[0]);
      const stats = await call("/api/stats");
      assert.equal(stats.body[entity.slug].count, 2);
      assert.equal(Object.values(stats.body[entity.slug].byStatus).reduce((a, b) => a + b, 0), 2);
    }
    assert.equal((await call(`/api/${entity.slug}/${created.body.record.id}`, { method: "DELETE" })).status, 200);
    assert.equal((await call(`/api/${entity.slug}/${created.body.record.id}`)).status, 404);
  }));

  test(`${entity.plural}: invalid input is rejected with a message`, () => withApp(async (call) => {
    const required = entity.fields.find((field) => field.required);
    if (required) {
      const missing = await call(`/api/${entity.slug}`, { method: "POST", body: JSON.stringify({ ...sample(entity), [required.key]: "" }) });
      assert.equal(missing.status, 400);
      assert.match(missing.body.errors[required.key], /required/u);
    }
    const email = entity.fields.find((field) => field.type === "email");
    if (email) assert.equal((await call(`/api/${entity.slug}`, { method: "POST", body: JSON.stringify({ ...sample(entity), [email.key]: "not-an-email" }) })).status, 400);
    const select = entity.fields.find((field) => field.type === "select");
    if (select) assert.equal((await call(`/api/${entity.slug}`, { method: "POST", body: JSON.stringify({ ...sample(entity), [select.key]: "Nonsense" }) })).status, 400);
    assert.equal((await call(`/api/${entity.slug}`, { method: "POST", body: "[1,2]" })).status, 400);
  }));
}

test("unknown record types and bad ids are 404s", () => withApp(async (call) => {
  assert.equal((await call("/api/nothing-here")).status, 404);
  if (config.entities[0]) assert.equal((await call(`/api/${config.entities[0].slug}/abc`)).status, 404);
}));
