import { spawnSync } from "node:child_process";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

// Generated by Atlas Genesis. Syntax-checks every JavaScript file, and fails on
// leftovers that should never ship: debugger statements and placeholder Latin.

const root = process.cwd();
const skip = new Set(["node_modules", "dist", "data", ".git", ".atlas"]);
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    if (skip.has(name)) continue;
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path);
    else if (/\.(m?js|html|css)$/u.test(name)) files.push(path);
  }
})(root);

let failures = 0;
for (const file of files) {
  if (/\.m?js$/u.test(file)) {
    const result = spawnSync(process.execPath, ["--check", file], { encoding: "utf8" });
    if (result.status !== 0) { failures += 1; console.error(`✗ ${relative(root, file)}\n${result.stderr}`); }
  }
  const text = readFileSync(file, "utf8");
  if (/\bdebugger\s*;/u.test(text)) { failures += 1; console.error(`✗ ${relative(root, file)}: remove the debugger statement`); }
  if (/lorem\s+ipsum/iu.test(text)) { failures += 1; console.error(`✗ ${relative(root, file)}: placeholder text`); }
}
if (failures) { console.error(`${failures} problem(s) in ${files.length} files.`); process.exit(1); }
console.log(`✓ ${files.length} files checked.`);
