import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Secrets } from "../src/secrets.mjs";

// Generated by Atlas Genesis. Manages data/secrets.json without putting a
// value on the command line (where shell history and process lists see it).
//
//   node scripts/secret.mjs list
//   node scripts/secret.mjs set NAME      then paste the value and press Ctrl+D
//   node scripts/secret.mjs remove NAME

const root = process.cwd();
let declared = [];
try { declared = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8")).secrets ?? []; } catch { /* no config */ }
const secrets = new Secrets({ file: join(root, "data", "secrets.json"), declared });
const [command, name] = process.argv.slice(2);

try {
  if (command === "list" || !command) {
    for (const entry of secrets.status()) console.log(`${entry.configured ? "✓" : "✗"} ${entry.name}${entry.source ? ` (${entry.source})` : ""}`);
  } else if (command === "set" && name) {
    if (process.stdin.isTTY) console.error(`Paste the value for ${name}, then press Enter and Ctrl+D:`);
    secrets.set(name, readFileSync(0, "utf8"));
    console.log(`✓ ${name} saved in data/secrets.json`);
  } else if (command === "remove" && name) {
    console.log(secrets.remove(name) ? `✓ ${name} removed` : `${name} was not set`);
  } else {
    console.error("Usage: node scripts/secret.mjs list | set NAME | remove NAME");
    process.exit(2);
  }
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
