import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Generated by Atlas Genesis (static-site template). Renders every page in
// site.json to dist/, with shared navigation, SEO basics and a sitemap.

const root = process.cwd();
const site = JSON.parse(readFileSync(join(root, "site.json"), "utf8"));
const dist = join(root, "dist");

const escape = (value) => String(value ?? "").replace(/[&<>"']/gu, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const fileFor = (page) => (page.id === "home" ? "index.html" : `${page.id}.html`);
const hrefFor = (page) => (page.id === "home" ? "/" : `/${page.id}.html`);

const problems = [];
if (!site.name) problems.push("site.json has no name");
if (!site.pages?.some((page) => page.id === "home")) problems.push("site.json needs a home page");
for (const page of site.pages ?? []) {
  if (!page.title || !page.headline) problems.push(`page ${page.id} needs a title and a headline`);
  if (!page.description || page.description.length > 160) problems.push(`page ${page.id} needs a description of at most 160 characters`);
}
if (problems.length) { console.error(`Build failed:\n- ${problems.join("\n- ")}`); process.exit(1); }

function section(block) {
  if (block.type === "cards") {
    return `<section class="band"><h2>${escape(block.title)}</h2><div class="cards">${block.items.map((item) => `<article class="card"><h3>${escape(item.title)}</h3><p>${escape(item.text)}</p></article>`).join("")}</div></section>`;
  }
  if (block.type === "steps") {
    return `<section class="band"><h2>${escape(block.title)}</h2><ol class="steps">${block.items.map((item) => `<li><strong>${escape(item.title)}</strong> ${escape(item.text)}</li>`).join("")}</ol></section>`;
  }
  if (block.type === "gallery") {
    return `<section class="band"><h2>${escape(block.title)}</h2><div class="gallery">${block.items.map((item) => `<figure class="tile"><div class="swatch" aria-hidden="true"></div><figcaption>${escape(item)}</figcaption></figure>`).join("")}</div><p class="note">${escape(block.note ?? "")}</p></section>`;
  }
  if (block.type === "contact") {
    return `<section class="band contact"><div><h2>${escape(block.title)}</h2><p>${escape(block.text)}</p><ul class="details">${site.contact.phone ? `<li>Phone: <a href="tel:${escape(site.contact.phone)}">${escape(site.contact.phone)}</a></li>` : ""}${site.contact.email ? `<li>Email: <a href="mailto:${escape(site.contact.email)}">${escape(site.contact.email)}</a></li>` : ""}${site.contact.area ? `<li>Service area: ${escape(site.contact.area)}</li>` : ""}</ul></div>
<form id="enquiry" class="card form" novalidate>
  <div class="field"><label for="name">Name *</label><input id="name" name="name" autocomplete="name" required></div>
  <div class="field"><label for="email">Email *</label><input id="email" name="email" type="email" autocomplete="email" required></div>
  <div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" autocomplete="tel"></div>
  <div class="field"><label for="message">How can we help? *</label><textarea id="message" name="message" rows="4" required></textarea></div>
  <p class="form-error" id="enquiry-error" role="alert" hidden></p>
  <button type="submit">Send enquiry</button>
</form>
<div class="card success" id="enquiry-done" role="status" hidden><h3>Thank you!</h3><p>We received your message and will reply soon.</p></div></section>`;
  }
  return `<section class="band"><h2>${escape(block.title)}</h2>${(block.paragraphs ?? []).map((p) => `<p>${escape(p)}</p>`).join("")}</section>`;
}

function render(page) {
  const nav = site.pages.map((item) => `<a href="${hrefFor(item)}"${item.id === page.id ? ' aria-current="page"' : ""}>${escape(item.title)}</a>`).join("");
  const hasForm = page.sections.some((block) => block.type === "contact");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(page.id === "home" ? `${site.name} · ${site.tagline}` : `${page.title} · ${site.name}`)}</title>
<meta name="description" content="${escape(page.description)}">
<link rel="canonical" href="${hrefFor(page)}">
<link rel="stylesheet" href="/styles.css">${hasForm ? '\n<script type="module" src="/contact.js"></script>' : ""}
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="topbar"><a class="brand" href="/">${escape(site.name)}</a><nav aria-label="Main">${nav}</nav></header>
<main id="main">
<section class="hero"><h1>${escape(page.headline)}</h1><p class="lead">${escape(page.intro)}</p>${page.id !== "contact" ? `<a class="button" href="/contact.html">${escape(site.cta)}</a>` : ""}</section>
${page.sections.map(section).join("\n")}
</main>
<footer class="footer"><p>© ${new Date().getFullYear()} ${escape(site.name)}${site.contact.area ? ` · ${escape(site.contact.area)}` : ""}</p></footer>
</body>
</html>
`;
}

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
for (const page of site.pages) writeFileSync(join(dist, fileFor(page)), render(page));
copyFileSync(join(root, "src", "styles.css"), join(dist, "styles.css"));
copyFileSync(join(root, "src", "contact.js"), join(dist, "contact.js"));
writeFileSync(join(dist, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${site.pages.map((page) => `  <url><loc>${escape(hrefFor(page))}</loc></url>`).join("\n")}\n</urlset>\n`);
writeFileSync(join(dist, "robots.txt"), "User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n");
console.log(`✓ Built ${site.pages.length} pages for ${site.name} into dist/`);
