"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AtlasMark } from "../AtlasMark.js";

type Workflow = "custom" | "job-application" | "sales-outreach" | "marketing";
type Device = { id: string; name: string; status: string; lastSeenAt: string | null; revokedAt: string | null };
type Task = { id: string; workflowType: Workflow; objective: string; status: string; result: string | null; error: string | null; createdAt: string };
type Approval = { id: string; summary: string; domain: string | null; expiresAt: string };
type Capabilities = { providers: { windows: { available: boolean }; cloudflare: { available: boolean; entitled: boolean; configured: boolean; monthlyMinutes: number | null } } };

const workflows: Array<{ id: Workflow; eyebrow: string; title: string; summary: string; startUrl: string; objective: string; guardrail: string }> = [
  { id: "job-application", eyebrow: "CAREER", title: "Apply for roles", summary: "Find strong-fit roles, prepare tailored answers, and complete forms.", startUrl: "https://www.linkedin.com/jobs/", objective: "Find roles matching my profile and preferences. For each strong match, summarize why it fits, prepare accurate tailored application answers, fill the form, and pause before every final submission.", guardrail: "You approve every application" },
  { id: "sales-outreach", eyebrow: "SALES", title: "Build qualified pipeline", summary: "Research prospects and prepare personal, evidence-based outreach.", startUrl: "https://www.linkedin.com/", objective: "Research qualified prospects for my offer, capture the source for each personalization detail, draft one-to-one outreach, and pause before sending or enrolling anyone in a sequence. Do not send bulk unsolicited messages.", guardrail: "You approve every send" },
  { id: "marketing", eyebrow: "GROWTH", title: "Operate campaigns", summary: "Draft posts, update listings, and prepare campaign changes across the web.", startUrl: "", objective: "Prepare the requested marketing work, verify claims against the provided source material, and pause before publishing, launching a campaign, or changing any spend.", guardrail: "You approve publish and spend" },
  { id: "custom", eyebrow: "GENERAL", title: "Run a browser task", summary: "Research, enter data, manage portals, and complete repeatable browser work.", startUrl: "", objective: "", guardrail: "Sensitive actions always pause" },
];

export function ComputerCenter() {
  const [devices, setDevices] = useState<Device[]>([]), [tasks, setTasks] = useState<Task[]>([]), [approvals, setApprovals] = useState<Approval[]>([]);
  const [credential, setCredential] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [provider, setProvider] = useState<"windows" | "cloudflare">("windows"), [capabilities, setCapabilities] = useState<Capabilities | null>(null);
  const [workflow, setWorkflow] = useState<Workflow>("job-application"), [objective, setObjective] = useState(workflows[0].objective), [startUrl, setStartUrl] = useState(workflows[0].startUrl);
  const refresh = useCallback(async () => {
    const [dr, tr] = await Promise.all([fetch("/api/computer/devices", { cache: "no-store" }), fetch("/api/computer/tasks", { cache: "no-store" })]);
    if (dr.status === 401 || tr.status === 401) { window.location.href = "/"; return; }
    if (!dr.ok || !tr.ok) throw new Error("Computer control is temporarily unavailable.");
    setDevices((await dr.json()).devices); const data = await tr.json(); setTasks(data.tasks); setApprovals(data.approvals); setCapabilities(data.capabilities);
  }, []);
  useEffect(() => { const first = window.setTimeout(() => void refresh().catch((e: Error) => setNotice(e.message)), 0); const timer = window.setInterval(() => void refresh(), 5000); return () => { window.clearTimeout(first); window.clearInterval(timer); }; }, [refresh]);
  function choose(next: Workflow) { const selected = workflows.find((item) => item.id === next)!; setWorkflow(next); setObjective(selected.objective); setStartUrl(selected.startUrl); }
  async function pair(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/computer/devices", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name") }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.message); setCredential(data.credential); setNotice("Paired. Copy the one-time credential into the companion now."); await refresh(); }
  async function queue(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/computer/tasks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ deviceId: form.get("deviceId"), executionProvider: provider, workflowType: workflow, objective, startUrl }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.message); setNotice("Task queued. Atlas will pause before any consequential action."); await refresh(); }
  async function decide(id: string, decision: "approved" | "rejected") { await fetch(`/api/computer/approvals/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision }) }); await refresh(); }
  async function cancel(id: string) { await fetch(`/api/computer/tasks/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "cancel" }) }); await refresh(); }
  async function revoke(id: string) { await fetch(`/api/computer/devices/${id}`, { method: "DELETE" }); await refresh(); }
  const active = workflows.find((item) => item.id === workflow)!;
  const availableDevices = devices.filter((device) => !device.revokedAt);
  return <main className="computer-shell operator-shell"><header className="setup-header"><Link className="brand" href="/"><span className="brandmark"><AtlasMark /></span>ATLAS</Link><nav><Link href="/">Workspace</Link><Link href="/setup">Connections</Link></nav></header>
    <section className="operator-hero"><div><div className="eyebrow"><span>COMPUTER OPERATOR</span> Work beyond the codebase</div><h1>Give Atlas a goal.<br/><em>Keep control of the click.</em></h1><p>Atlas works through a browser on your computer—or a hosted browser on paid plans. It researches, prepares, and fills in the work, then stops at the moments that carry consequence.</p></div><div className="operator-status"><span className={availableDevices.some((device)=>device.status==="online")?"online":""}/><b>{availableDevices.some((device)=>device.status==="online")?"Computer ready":"Pair a computer to begin"}</b><small>Read-only steps can run autonomously. Submissions, sends, publishing, purchases, uploads, and account changes require approval.</small></div></section>
    {notice && <p className="computer-notice" role="status">{notice}</p>}
    {approvals.length > 0 && <section className="approval-stack"><div className="eyebrow"><span>YOUR MOVE</span> Atlas is paused</div>{approvals.map((approval) => <article key={approval.id}><div><strong>{approval.summary}</strong><small>{approval.domain ?? "Local browser"} · expires {new Date(approval.expiresAt).toLocaleTimeString()}</small></div><div><button className="quiet" onClick={() => void decide(approval.id, "rejected")}>Reject</button><button onClick={() => void decide(approval.id, "approved")}>Approve once</button></div></article>)}</section>}
    <section className="operator-section"><div className="section-heading"><div><span>01</span><h2>Choose the outcome</h2></div><p>Purpose-built playbooks give the operator clear boundaries before it starts.</p></div><div className="workflow-grid">{workflows.map((item)=><button key={item.id} className={workflow===item.id?"active":""} onClick={()=>choose(item.id)}><small>{item.eyebrow}</small><strong>{item.title}</strong><span>{item.summary}</span><em>{item.guardrail}</em></button>)}</div></section>
    <section className="operator-console"><div className="operator-form"><div className="section-heading"><div><span>02</span><h2>Set the mission</h2></div></div><form onSubmit={queue}><div className="operator-form-row"><label>Runs on<select aria-label="Browser execution provider" value={provider} onChange={(event) => setProvider(event.target.value as "windows" | "cloudflare")}><option value="windows">My Windows PC · included</option><option value="cloudflare" disabled={!capabilities?.providers.cloudflare.available}>Hosted browser{!capabilities?.providers.cloudflare.entitled ? " · Pro required" : !capabilities?.providers.cloudflare.configured ? " · activating soon" : ` · ${capabilities.providers.cloudflare.monthlyMinutes ?? "metered"} min/mo`}</option></select></label>{provider === "windows" && <label>Computer<select name="deviceId" required defaultValue=""><option value="" disabled>Choose a paired PC</option>{availableDevices.map((device) => <option key={device.id} value={device.id}>{device.name} · {device.status}</option>)}</select></label>}</div><label>Start here <span>optional</span><input value={startUrl} onChange={(event)=>setStartUrl(event.target.value)} type="url" placeholder="https://…" /></label><label>What should Atlas accomplish?<textarea value={objective} onChange={(event)=>setObjective(event.target.value)} rows={7} maxLength={2000} required /></label><div className="mission-footer"><p><b>Approval policy</b><br/>{active.guardrail}. Atlas also pauses for purchases, sensitive uploads, and account or security changes.</p><button disabled={busy || (provider === "windows" && !availableDevices.length) || (provider === "cloudflare" && !capabilities?.providers.cloudflare.available)}>{busy?"Queueing…":"Start operator"}</button></div></form></div><aside className="trust-card"><small>BUILT-IN BOUNDARIES</small><h3>Autonomous where safe.<br/>Accountable everywhere.</h3><ul><li><b>Research and prepare</b><span>Browse, compare, summarize, and fill drafts without interrupting you.</span></li><li><b>Approve the consequence</b><span>Every send, submission, publish, purchase, or sensitive change pauses.</span></li><li><b>One approval, one action</b><span>Approvals expire and are cryptographically bound to the exact proposed action.</span></li><li><b>No spam or deception</b><span>Bulk unsolicited outreach, false claims, and safeguard bypasses are prohibited.</span></li></ul></aside></section>
    <section className="computer-grid pairing-grid"><article className="control-card"><span className="card-index">03</span><h2>Pair Windows</h2><p>Name this PC, then paste the one-time credential into the companion. Atlas stores only its fingerprint.</p><form onSubmit={pair}><label>Computer name<input name="name" defaultValue="My Windows PC" maxLength={80} required /></label><button disabled={busy}>Create pairing</button></form>{credential && <div className="credential"><small>Shown once</small><code>{credential}</code><button onClick={() => void navigator.clipboard.writeText(credential)}>Copy</button></div>}<ul className="device-list">{availableDevices.map((device) => <li key={device.id}><span>{device.name}<small>{device.status}</small></span><button className="device-revoke" onClick={()=>void revoke(device.id)}>Revoke</button></li>)}</ul></article><article className="control-card dark"><span className="card-index">HOW IT WORKS</span><h2>Your session stays yours.</h2><p>The Windows companion uses a separate browser profile on your PC. Atlas receives only the task state and approval requests needed to coordinate the work.</p><ol className="operator-steps"><li>Pair once with a one-time credential.</li><li>Send work from desktop or phone.</li><li>Approve consequential actions from Atlas.</li><li>Review the result and activity history.</li></ol></article></section>
    <section className="computer-history"><div className="eyebrow"><span>RECENT</span> Operator runs</div>{tasks.length === 0 ? <p>No computer tasks yet.</p> : tasks.map((task) => <article key={task.id}><span className={`task-status ${task.status}`}>{task.status}</span><div><small>{workflows.find((item)=>item.id===task.workflowType)?.title ?? "Browser task"}</small><strong>{task.objective}</strong>{(task.result || task.error) && <p>{task.result ?? task.error}</p>}</div><div className="history-end"><time>{new Date(task.createdAt).toLocaleString()}</time>{["queued","running"].includes(task.status)&&<button onClick={()=>void cancel(task.id)}>Cancel</button>}</div></article>)}</section></main>;
}
