"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AtlasMark } from "../AtlasMark.js";

type Device = { id: string; name: string; status: string; lastSeenAt: string | null; revokedAt: string | null };
type Task = { id: string; objective: string; status: string; result: string | null; error: string | null; createdAt: string };
type Approval = { id: string; summary: string; domain: string | null; expiresAt: string };
type Capabilities = { providers: { windows: { available: boolean }; cloudflare: { available: boolean; entitled: boolean; configured: boolean; monthlyMinutes: number | null } } };

export function ComputerCenter() {
  const [devices, setDevices] = useState<Device[]>([]), [tasks, setTasks] = useState<Task[]>([]), [approvals, setApprovals] = useState<Approval[]>([]);
  const [credential, setCredential] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [provider, setProvider] = useState<"windows" | "cloudflare">("windows"), [capabilities, setCapabilities] = useState<Capabilities | null>(null);
  const refresh = useCallback(async () => {
    const [dr, tr] = await Promise.all([fetch("/api/computer/devices", { cache: "no-store" }), fetch("/api/computer/tasks", { cache: "no-store" })]);
    if (dr.status === 401 || tr.status === 401) { window.location.href = "/"; return; }
    if (!dr.ok || !tr.ok) throw new Error("Computer control is temporarily unavailable.");
    setDevices((await dr.json()).devices); const data = await tr.json(); setTasks(data.tasks); setApprovals(data.approvals); setCapabilities(data.capabilities);
  }, []);
  useEffect(() => { const first = window.setTimeout(() => void refresh().catch((e: Error) => setNotice(e.message)), 0); const timer = window.setInterval(() => void refresh(), 5000); return () => { window.clearTimeout(first); window.clearInterval(timer); }; }, [refresh]);
  async function pair(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/computer/devices", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name") }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.message); setCredential(data.credential); setNotice("Paired. Copy the one-time credential into the companion now."); await refresh(); }
  async function queue(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/computer/tasks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ deviceId: form.get("deviceId"), executionProvider: provider, objective: form.get("objective"), startUrl: form.get("startUrl") }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.message); event.currentTarget.reset(); setNotice(`Browser task queued on ${provider === "windows" ? "Windows" : "Cloudflare"}.`); await refresh(); }
  async function decide(id: string, decision: "approved" | "rejected") { await fetch(`/api/computer/approvals/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision }) }); await refresh(); }
  return <main className="computer-shell"><header className="setup-header"><Link className="brand" href="/"><span className="brandmark"><AtlasMark /></span>ATLAS</Link><Link href="/setup">Setup center</Link></header>
    <section className="computer-head"><div><div className="eyebrow"><span>COMPUTER</span> Phone-to-PC control</div><h1>Your browser,<br /><em>within reach.</em></h1></div><p>Queue work from your phone. A paired Windows companion runs it in a separate browser profile and pauses before consequential actions.</p></section>
    {notice && <p className="computer-notice" role="status">{notice}</p>}
    {approvals.length > 0 && <section className="approval-stack"><div className="eyebrow"><span>WAITING</span> Needs your decision</div>{approvals.map((a) => <article key={a.id}><div><strong>{a.summary}</strong><small>{a.domain ?? "Local browser"} · expires {new Date(a.expiresAt).toLocaleTimeString()}</small></div><div><button className="quiet" onClick={() => void decide(a.id, "rejected")}>Reject</button><button onClick={() => void decide(a.id, "approved")}>Approve once</button></div></article>)}</section>}
    <section className="computer-grid"><article className="control-card"><span className="card-index">01</span><h2>Pair Windows</h2><p>Name this PC, then paste the one-time credential into the companion. Atlas stores only its fingerprint.</p><form onSubmit={pair}><label>Computer name<input name="name" defaultValue="My Windows PC" maxLength={80} required /></label><button disabled={busy}>Create pairing</button></form>{credential && <div className="credential"><small>Shown once</small><code>{credential}</code><button onClick={() => void navigator.clipboard.writeText(credential)}>Copy</button></div>}<ul className="device-list">{devices.filter((d) => !d.revokedAt).map((d) => <li key={d.id}><span>{d.name}</span><b>{d.status}</b></li>)}</ul></article>
      <article className="control-card dark"><span className="card-index">02</span><h2>Send browser work</h2><p>Windows is the default. Switch to a hosted browser when your PC is offline.</p><form onSubmit={queue}><label>Runs on<select aria-label="Browser execution provider" value={provider} onChange={(event) => setProvider(event.target.value as "windows" | "cloudflare")}><option value="windows">My Windows PC · included</option><option value="cloudflare" disabled={!capabilities?.providers.cloudflare.available}>Cloudflare hosted browser{!capabilities?.providers.cloudflare.entitled ? " · Pro required" : !capabilities?.providers.cloudflare.configured ? " · activating soon" : ` · ${capabilities.providers.cloudflare.monthlyMinutes ?? "metered"} min/mo`}</option></select></label>{provider === "windows" && <label>Computer<select name="deviceId" required defaultValue=""><option value="" disabled>Choose a paired PC</option>{devices.filter((d) => !d.revokedAt).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}<label>Start URL<input name="startUrl" type="url" placeholder="https://…" /></label><label>Objective<textarea name="objective" rows={5} maxLength={2000} placeholder="Open the setup page, check the failed step, and stop before changing permissions." required /></label><button disabled={busy || (provider === "cloudflare" && !capabilities?.providers.cloudflare.available)}>Queue on {provider === "windows" ? "Windows" : "Cloudflare"}</button></form></article></section>
    <section className="computer-history"><div className="eyebrow"><span>RECENT</span> Browser tasks</div>{tasks.length === 0 ? <p>No browser tasks yet.</p> : tasks.map((t) => <article key={t.id}><span className={`task-status ${t.status}`}>{t.status}</span><div><strong>{t.objective}</strong>{(t.result || t.error) && <p>{t.result ?? t.error}</p>}</div><time>{new Date(t.createdAt).toLocaleString()}</time></article>)}</section></main>;
}
