import type { Metadata } from "next";
import Link from "next/link";
import { MarketingFooter, MarketingNav } from "../MarketingNav.js";

export const metadata: Metadata = {
  title: "Login, controls & safety — Atlas",
  description: "How to sign in, control Atlas missions, approve computer actions, and understand Atlas self-modification safeguards.",
};

const controls = [
  ["Choose the right mode", "Use Plan to turn an outcome into steps, Debug to investigate a failure, and Build to create verified changes. Repository and branch selectors keep the target visible."],
  ["Run durable missions", "Mission Control shows child agents, dependencies, budgets, checkpoints, artifacts, and evidence. Pause, resume, or cancel the mission without losing its recorded state."],
  ["Approve consequential actions", "Atlas pauses before sending, submitting, publishing, purchasing, uploading, changing infrastructure, or exposing credentials. Approval is tied to the exact proposed action—not a blank check."],
  ["Inspect before trusting", "Review the diff, test results, browser evidence, audit history, and destination before approving or merging. Atlas reports verified evidence separately from model narration."],
];

export default function GuidePage() {
  return <main><MarketingNav />
    <section className="marketing-hero compact guide-hero"><p className="eyebrow"><span>CONTROL GUIDE</span> Access, operate, verify</p><h1>Powerful enough to act.<br /><em>Bounded enough to trust.</em></h1><p>Atlas can build software, coordinate parallel agents, and operate a computer. This guide shows which login to use, where control stays with you, and why a customer cannot quietly turn Atlas against its own deployment.</p><div className="hero-actions"><Link href="/owner">Owner sign-in</Link><Link className="quiet" href="/api/auth/github/start">Customer sign-in</Link></div></section>
    <section className="guide-section"><div className="guide-heading"><p className="eyebrow"><span>01</span> Sign in</p><h2>Three access paths. Three separate trust boundaries.</h2></div><div className="guide-cards"><article><b>Deployment owner</b><p>Open <Link href="/owner">Owner access</Link> and continue with the exact GitHub login configured in the deployment owner allowlist. A private access code is the recovery path. The owner seat has no subscription limits, but safety policy and audit controls remain active.</p></article><article><b>Atlas customer</b><p>Choose customer sign-in with GitHub. Your account receives its own data scope, plan, tasks, conversations, and devices. Buying a plan increases product capacity; it does not create owner or deployment authority.</p></article><article><b>Local companion</b><p>Run the Windows companion and unlock its local control plane with the device-local admin token. Phone pairing creates a separate, revocable credential so the administrator token never has to leave the computer.</p></article></div></section>
    <section className="guide-section guide-dark"><div className="guide-heading"><p className="eyebrow"><span>02</span> Operate</p><h2>You direct the outcome. Atlas exposes the controls.</h2></div><div className="guide-control-list">{controls.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="guide-section"><div className="guide-heading"><p className="eyebrow"><span>03</span> Self-improvement</p><h2>Yes—Atlas can help build Atlas. It cannot silently appoint a customer as its owner.</h2></div><div className="guide-split"><div><h3>The controlled path</h3><ol><li>The deployment owner requests a Build mission against a protected Atlas repository.</li><li>Atlas works on an isolated branch or worktree and records the mission.</li><li>Builds, tests, security checks, and policy checks evaluate the change.</li><li>The result becomes a reviewable pull request—not an invisible production mutation.</li><li>Merge and deployment follow the repository’s configured review policy.</li></ol></div><div><h3>What blocks a random client</h3><ul><li>Only the explicit deployment-owner identity may run coding mode against protected self repositories.</li><li>Repository allowlists and merge-policy settings are owner-only.</li><li>Customer records and task state are scoped to their authenticated principal.</li><li>Secrets stay server-side and are not returned to browser clients.</li><li>Paid plans grant capacity, never administrative privilege.</li></ul></div></div></section>
    <section className="guide-section guide-boundaries"><div className="guide-heading"><p className="eyebrow"><span>04</span> Honest boundaries</p><h2>Safeguards reduce risk. They do not eliminate the need for ownership discipline.</h2></div><div className="guide-cards"><article><b>Protect the trust roots</b><p>GitHub organization owners, Cloudflare administrators, deployment secrets, and the configured owner identity remain privileged. Use hardware-backed MFA, least-privilege credentials, rotation, and account recovery controls.</p></article><article><b>Keep branch protection on</b><p>Require pull requests, status checks, and review for the default branch. Do not give an automation token permission to bypass the very controls intended to review it.</p></article><article><b>Treat model output as untrusted</b><p>Models can be wrong or manipulated. Keep consequential-action approvals narrow, inspect evidence, test backups and rollback, and revoke sessions or paired devices you no longer recognize.</p></article></div></section>
    <section className="closing-cta"><p>Autonomy without surrender.</p><h2>Give Atlas the mission.<br />Keep the authority.</h2><Link href="/computer">Open the computer operator →</Link></section><MarketingFooter /></main>;
}
