import type { Metadata } from "next";
import Link from "next/link";
import { MarketingFooter, MarketingNav } from "../MarketingNav.js";

export const metadata: Metadata = {
  title: "Safety — Atlas",
  description: "How you sign in, what Atlas asks before doing, how code changes are merged, and what you should still protect yourself.",
};

const controls = [
  ["It asks before important actions", "Before Atlas sends, submits, publishes, buys, uploads, changes infrastructure, or uses a password, it stops and asks. Each approval covers that one action only."],
  ["Code arrives as a pull request", "Atlas never edits your main branch directly. It works on its own branch, runs your tests, and opens a pull request you can read."],
  ["You choose how merging works", "Per project: merge only after you review, merge automatically once every test passes, or merge right away."],
  ["You can see what happened", "Every task keeps a record of its steps, test results, and approvals. Atlas reports what it can verify, not just what the AI said."],
];

export default function GuidePage() {
  return <main><MarketingNav />
    <section className="marketing-hero compact guide-hero"><p className="eyebrow"><span>SAFETY</span> How Atlas keeps you in control</p><h1>Atlas can act.<br /><em>You decide how far.</em></h1><p>This page explains how you sign in, what Atlas checks with you before doing, how its code changes get merged, and what you should still protect on your side.</p><div className="hero-actions"><Link href="/">Sign in</Link><Link className="quiet" href="/owner">Owner sign-in</Link></div></section>
    <section className="guide-section"><div className="guide-heading"><p className="eyebrow"><span>01</span> Signing in</p><h2>Three ways in, each with its own permissions.</h2></div><div className="guide-cards"><article><b>Customers</b><p>Sign in with GitHub. Your chats, tasks, projects, and computers are only visible to your account. Upgrading your plan raises your limits; it never gives you admin access.</p></article><article><b>The owner</b><p>The person who runs this Atlas deployment signs in on <Link href="/owner">Owner sign-in</Link> with the GitHub account set as owner, or with a private access code. Only the owner can point Atlas at Atlas&rsquo;s own code.</p></article><article><b>Your computer</b><p>The Windows companion app connects your PC with a one-time pairing file. You can disconnect it at any time on the Computer control page.</p></article></div></section>
    <section className="guide-section guide-dark"><div className="guide-heading"><p className="eyebrow"><span>02</span> While Atlas works</p><h2>What Atlas does on its own, and what it asks you first.</h2></div><div className="guide-control-list">{controls.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="guide-section"><div className="guide-heading"><p className="eyebrow"><span>03</span> Atlas working on itself</p><h2>Atlas improves its own code, within limits it cannot change.</h2></div><div className="guide-split"><div><h3>How it works</h3><ol><li>The owner asks Atlas, in chat or on a daily schedule, to improve something about itself.</li><li>Atlas makes the change on a separate branch.</li><li>It runs the project&rsquo;s tests before and after its change.</li><li>It opens a pull request. By default the pull request merges itself once every automated check passes; the owner can switch this to manual review.</li><li>If a check fails, or Atlas&rsquo;s own tests show it broke something, the pull request stays open for a person.</li></ol></div><div><h3>What it can&rsquo;t do</h3><ul><li>Merge its own change without every check passing.</li><li>Choose its own merge rule: that is set by the owner, outside Atlas.</li><li>Let anyone except the owner start work on Atlas&rsquo;s code.</li><li>See or return secret keys to the browser.</li><li>Turn a paid plan into admin access.</li></ul></div></div></section>
    <section className="guide-section guide-boundaries"><div className="guide-heading"><p className="eyebrow"><span>04</span> Your side</p><h2>Atlas lowers the risk. A few things are still up to you.</h2></div><div className="guide-cards"><article><b>Protect your accounts</b><p>Use two-factor authentication on GitHub and Cloudflare, give Atlas only the access it needs, and rotate keys you no longer trust.</p></article><article><b>Keep branch protection on</b><p>Require passing checks before anything merges to your main branch, so no automation, including Atlas, can skip them.</p></article><article><b>Double-check what matters</b><p>AI can be wrong or misled by what it reads online. Read approval requests before you accept them, and remove devices or sessions you don&rsquo;t recognize.</p></article></div></section>
    <section className="closing-cta"><p>Questions about safety?</p><h2>Ask us anything.</h2><Link href="/about">About Atlas →</Link></section><MarketingFooter /></main>;
}
