import { appendFileSync, mkdirSync } from "node:fs";
import { createServer } from "node:http";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readJson, sendJson, serveStatic } from "./src/http.mjs";

// Generated by Atlas Genesis (static-site template). Serves the built pages in
// dist/ and records enquiries from the contact form in data/enquiries.jsonl.

const here = dirname(fileURLToPath(import.meta.url));
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/u;

export function validateEnquiry(input) {
  const errors = {};
  const clean = {};
  for (const key of ["name", "email", "phone", "message"]) clean[key] = typeof input[key] === "string" ? input[key].trim().slice(0, 2000) : "";
  if (!clean.name) errors.name = "Please tell us your name.";
  if (!EMAIL.test(clean.email)) errors.email = "Please enter a valid email address.";
  if (!clean.message) errors.message = "Please tell us how we can help.";
  return { clean, errors };
}

export function createApp({ distDir = join(here, "dist"), enquiriesFile = join(here, "data", "enquiries.jsonl") } = {}) {
  return createServer(async (request, response) => {
    const url = new URL(request.url ?? "/", "http://localhost");
    try {
      if (url.pathname === "/api/health") return sendJson(response, 200, { ok: true });
      if (url.pathname === "/api/enquiries") {
        if (request.method !== "POST") return sendJson(response, 405, { error: "Method not allowed." });
        const { clean, errors } = validateEnquiry(await readJson(request));
        if (Object.keys(errors).length) return sendJson(response, 400, { error: Object.values(errors)[0], errors });
        if (enquiriesFile) {
          mkdirSync(dirname(enquiriesFile), { recursive: true });
          appendFileSync(enquiriesFile, `${JSON.stringify({ ...clean, receivedAt: new Date().toISOString() })}\n`);
        }
        return sendJson(response, 201, { received: true });
      }
      if (request.method !== "GET" && request.method !== "HEAD") return sendJson(response, 405, { error: "Method not allowed." });
      return await serveStatic(response, distDir, url.pathname);
    } catch (error) {
      return sendJson(response, error.status ?? 500, { error: error.status ? error.message : "Something went wrong." });
    }
  });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const port = Number(process.env.PORT || 3000);
  const host = process.env.HOST || "127.0.0.1";
  createApp().listen(port, host, () => console.log(`Site running at http://${host}:${port}`));
}
