export const LOCAL_UI_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Atlas Local</title><link rel="stylesheet" href="/app.css"></head>
<body><main><header><div><p class="eyebrow">SOVEREIGN CONTROL PLANE</p><h1>Atlas Local</h1></div><span id="health">Checking model…</span></header>
<section class="panel"><h2>Local access</h2><label>Access token<input id="token" type="password" autocomplete="off" placeholder="Paste the token printed at first launch"></label><button id="save-token">Unlock this tab</button><p class="hint">Stored only for this browser tab. Atlas binds to this computer by default.</p></section>
<section class="panel"><h2>Run local coder</h2><form id="task-form"><label>Repository folder<input id="repository" required placeholder="C:\\path\\to\\project"></label><label>Objective<textarea id="objective" required maxlength="10000" placeholder="Describe one bounded change"></textarea></label><label>Model<input id="model" value="qwen2.5-coder:7b"></label><button>Queue isolated task</button></form><p id="notice" role="status"></p></section>
<section><div class="section-title"><h2>Tasks</h2><button class="secondary" id="refresh">Refresh</button></div><div id="tasks" class="tasks"><p class="empty">Unlock this tab to load tasks.</p></div></section>
</main><script type="module" src="/app.js"></script></body></html>`;

export const LOCAL_UI_CSS = `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#eff5ef;background:#0d120f;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#24372b 0,transparent 35%),#0d120f;min-height:100vh}main{width:min(760px,calc(100% - 32px));margin:auto;padding:32px 0 72px}header,.section-title{display:flex;align-items:center;justify-content:space-between;gap:20px}h1{font-size:clamp(2.4rem,8vw,4.6rem);line-height:.9;margin:5px 0 30px;letter-spacing:-.06em}h2{font-size:1.05rem;margin:0 0 18px}.eyebrow,.hint,time{font-size:.75rem;color:#9aafa0;letter-spacing:.12em}.panel,.task{border:1px solid #33443a;background:#141c17;border-radius:16px;padding:22px;margin:0 0 18px;box-shadow:0 20px 70px #0004}label{display:grid;gap:7px;margin:0 0 15px;color:#bfd0c3;font-size:.9rem}input,textarea,button{font:inherit;border-radius:9px}input,textarea{width:100%;border:1px solid #405247;background:#0d120f;color:#fff;padding:12px}textarea{min-height:110px;resize:vertical}button{border:0;background:#d8ff8f;color:#14200f;font-weight:750;padding:11px 16px;cursor:pointer}.secondary{background:#26352b;color:#dfe9e1}.hint,#notice{margin:12px 0 0}.tasks{display:grid;gap:12px}.task{margin:0}.task-top{display:flex;justify-content:space-between;gap:14px}.task h3{font-size:1rem;margin:0;overflow-wrap:anywhere}.task p{color:#b8c6bb;white-space:pre-wrap;overflow-wrap:anywhere}.status{font-size:.72rem;text-transform:uppercase;letter-spacing:.09em;color:#d8ff8f}.status.failed,.status.interrupted{color:#ffb0a7}.empty{color:#91a397}@media(max-width:560px){main{width:min(100% - 22px,760px);padding-top:20px}header{align-items:flex-start;flex-direction:column;gap:0}.panel,.task{padding:17px}}`;

export const LOCAL_UI_JS = `const tokenInput=document.querySelector('#token'),tasks=document.querySelector('#tasks'),notice=document.querySelector('#notice');tokenInput.value=sessionStorage.getItem('atlas-token')||'';const headers=()=>({authorization:'Bearer '+sessionStorage.getItem('atlas-token')});async function load(){const r=await fetch('/v1/tasks',{headers:headers()});if(r.status===401){tasks.innerHTML='<p class="empty">Unlock this tab to load tasks.</p>';return}const {tasks:list}=await r.json();tasks.innerHTML=list.length?list.map(t=>'<article class="task"><div class="task-top"><h3>'+escapeHtml(t.objective)+'</h3><span class="status '+t.status+'">'+t.status+'</span></div><p>'+escapeHtml(t.repository)+' · '+escapeHtml(t.model)+'</p>'+(t.message?'<p>'+escapeHtml(t.message)+'</p>':'')+'<time>'+new Date(t.createdAt).toLocaleString()+'</time></article>').join(''):'<p class="empty">No local tasks yet.</p>'}function escapeHtml(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}document.querySelector('#save-token').onclick=()=>{sessionStorage.setItem('atlas-token',tokenInput.value);load()};document.querySelector('#refresh').onclick=load;document.querySelector('#task-form').onsubmit=async e=>{e.preventDefault();notice.textContent='Queueing…';const r=await fetch('/v1/tasks',{method:'POST',headers:{...headers(),'content-type':'application/json'},body:JSON.stringify({repository:document.querySelector('#repository').value,objective:document.querySelector('#objective').value,model:document.querySelector('#model').value})});const data=await r.json();notice.textContent=r.ok?'Task queued in an isolated worktree.':data.message;load()};fetch('/health').then(r=>r.json()).then(v=>document.querySelector('#health').textContent=v.status==='ok'?v.model+' ready':'Unavailable').catch(()=>document.querySelector('#health').textContent='Unavailable');if(tokenInput.value)load();setInterval(()=>{if(sessionStorage.getItem('atlas-token'))load()},5000);`;
