import type { Metadata } from "next";
import Link from "next/link";
import { MarketingFooter, MarketingNav } from "../MarketingNav.js";
export const metadata: Metadata = { title: "Pricing — Atlas", description: "Atlas is free to start. Pro and Team add code changes, a hosted browser, and higher limits." };
const plans = [
  { name: "Free", price: "$0", line: "Try Atlas on your own projects.", features: ["Chat with saved history", "Project reviews and debugging", "Browser tasks on your own Windows PC", "Approval before every important action"], cta: "Start free" },
  { name: "Pro", price: "$19", line: "For people building and shipping on their own.", features: ["Everything in Free", "Code changes delivered as pull requests", "Hosted browser, no PC needed", "More tasks per month"], cta: "Choose Pro", featured: true },
  { name: "Team", price: "$59", line: "For small teams sharing one account.", features: ["Everything in Pro", "More seats", "Higher monthly limits", "Priority support"], cta: "Choose Team" },
];
export default function PricingPage(){return <main><MarketingNav/><section className="marketing-hero compact"><p className="eyebrow"><span>PRICING</span> Simple monthly plans</p><h1>Free to start.<br/><em>Upgrade when you need more.</em></h1><p>Every plan includes approvals before important actions. Your code and accounts stay yours on every plan, including Free.</p></section><section className="pricing-grid">{plans.map(plan=><article key={plan.name} className={plan.featured?"featured":""}>{plan.featured&&<mark>MOST POPULAR</mark>}<h2>{plan.name}</h2><div className="price">{plan.price}<small>{plan.price!=="$0"?" / month":" forever"}</small></div><p>{plan.line}</p><ul>{plan.features.map(item=><li key={item}>{item}</li>)}</ul><Link href="/api/auth/github/start">{plan.cta} →</Link></article>)}</section><section className="pricing-note"><b>Good to know</b><p>Paid checkout turns on once billing is set up for this deployment. Team currently differs from Pro in seats and limits, not features. Hosted-browser minutes may change as we learn real costs.</p></section><MarketingFooter/></main>}
