import { readFileSync } from "node:fs";
import { createServer } from "node:http";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createBackend } from "./src/backend.mjs";
import { readJson, sendJson, serveStatic } from "./src/http.mjs";
import { RecordStore } from "./src/store.mjs";

// Generated by Atlas Genesis (web-app template). The pages, record types,
// fields, sign-in, files, secrets and jobs come from app.config.json.

const here = dirname(fileURLToPath(import.meta.url));
export const config = JSON.parse(readFileSync(join(here, "app.config.json"), "utf8"));

export function createApp({ dataFile = join(here, "data", "app.sqlite"), publicDir = join(here, "public"), filesDir, secretsFile = join(here, "data", "secrets.json"), env = process.env, runJobs = false } = {}) {
  const store = new RecordStore(config.entities, dataFile);
  const backend = createBackend({
    config, dataFile, filesDir, secretsFile, env,
    // The work of each scheduled job in app.config.json "jobs" (sign-in's session clean-up is built in).
    jobs: {},
    // Signed out, a booking app still accepts new bookings.
    isPublic: (request, slug, id) => Boolean(config.booking && slug === config.booking.entity && !id && request.method === "POST"),
  });
  const server = createServer(async (request, response) => {
    const url = new URL(request.url ?? "/", "http://localhost");
    try {
      if (!url.pathname.startsWith("/api/")) {
        if (request.method !== "GET" && request.method !== "HEAD") return sendJson(response, 405, { error: "Method not allowed." });
        return await serveStatic(response, publicDir, url.pathname, { fallback: "index.html" });
      }
      if ((await backend.route(request, response, url)).handled) return;
      const [, , slug, id, extra] = url.pathname.split("/");
      if (extra !== undefined) return sendJson(response, 404, { error: "Not found." });
      if (slug === "health" && request.method === "GET") return sendJson(response, 200, { ok: true, name: config.name });
      if (slug === "config" && request.method === "GET") return sendJson(response, 200, config);
      if (slug === "stats" && request.method === "GET") return sendJson(response, 200, store.stats());
      store.entity(slug);
      if (!id) {
        if (request.method === "GET") return sendJson(response, 200, { records: store.list(slug, { q: url.searchParams.get("q") ?? "" }) });
        if (request.method === "POST") return sendJson(response, 201, { record: store.create(slug, await readJson(request)) });
        return sendJson(response, 405, { error: "Method not allowed." });
      }
      if (!/^\d{1,12}$/u.test(id)) return sendJson(response, 404, { error: "Not found." });
      if (request.method === "GET") {
        const record = store.get(slug, id);
        return record ? sendJson(response, 200, { record }) : sendJson(response, 404, { error: "Not found." });
      }
      if (request.method === "PATCH" || request.method === "PUT") {
        const record = store.update(slug, id, await readJson(request));
        return record ? sendJson(response, 200, { record }) : sendJson(response, 404, { error: "Not found." });
      }
      if (request.method === "DELETE") return store.remove(slug, id) ? sendJson(response, 200, { deleted: true }) : sendJson(response, 404, { error: "Not found." });
      return sendJson(response, 405, { error: "Method not allowed." });
    } catch (error) {
      const status = error.status ?? 500;
      if (status >= 500) console.error(error);
      return sendJson(response, status, { error: status >= 500 ? "Something went wrong." : error.message, ...(error.errors ? { errors: error.errors } : {}) });
    }
  });
  if (runJobs) backend.scheduler.start();
  server.on("close", () => {
    backend.close();
    store.close();
  });
  return server;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const port = Number(process.env.PORT || 3000);
  const host = process.env.HOST || "127.0.0.1";
  createApp({ runJobs: true }).listen(port, host, () => console.log(`${config.name} is running at http://${host}:${port}`));
}
