import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Generated by Atlas Genesis (api-service template). Checks the configuration
// and produces dist/ with the server and its modules.

const root = process.cwd();
const config = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8"));
const problems = [];
if (!config.name) problems.push("app.config.json has no name");
if (!config.entities?.length) problems.push("app.config.json has no record types");
for (const entity of config.entities ?? []) for (const field of entity.fields ?? []) if (field.type === "select" && !field.options?.length) problems.push(`${entity.name}.${field.key} has no options`);
if (problems.length) { console.error(`Build failed:\n- ${problems.join("\n- ")}`); process.exit(1); }
const dist = join(root, "dist");
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
for (const entry of ["server.mjs", "app.config.json", "package.json", "src"]) if (existsSync(join(root, entry))) cpSync(join(root, entry), join(dist, entry), { recursive: true });
writeFileSync(join(dist, "build-info.json"), `${JSON.stringify({ name: config.name, builtAt: new Date().toISOString() }, null, 2)}\n`);
console.log(`✓ Built ${config.name} into dist/`);
