import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createApp, validateEnquiry } from "../server.mjs";

// Generated by Atlas Genesis (static-site template).

const root = process.cwd();
const site = JSON.parse(readFileSync(join(root, "site.json"), "utf8"));

test("the build renders every page with a title, description, heading and navigation", () => {
  const result = spawnSync(process.execPath, ["scripts/build.mjs"], { cwd: root, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr);
  for (const page of site.pages) {
    const file = join(root, "dist", page.id === "home" ? "index.html" : `${page.id}.html`);
    assert.ok(existsSync(file), `${page.id} was built`);
    const html = readFileSync(file, "utf8");
    assert.match(html, /<title>[^<]+<\/title>/u);
    assert.match(html, /<meta name="description" content="[^"]+">/u);
    const escape = (value) => String(value).replace(/[&<>"']/gu, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
    assert.ok(html.includes(`<h1 data-atlas-source="${escape(page.id)}:headline">${escape(page.headline)}</h1>`), `${page.id} has its configured heading and source identity`);
    for (const other of site.pages) assert.ok(html.includes(other.id === "home" ? 'href="/"' : `href="/${other.id}.html"`), `${page.id} links to ${other.id}`);
  }
  const sitemap = readFileSync(join(root, "dist", "sitemap.xml"), "utf8");
  assert.equal((sitemap.match(/<url>/gu) ?? []).length, site.pages.length);
});

test("the enquiry form validates and records submissions", async () => {
  assert.deepEqual(Object.keys(validateEnquiry({}).errors).sort(), ["email", "message", "name"]);
  const directory = mkdtempSync(join(tmpdir(), "site-"));
  const server = createApp({ distDir: join(root, "dist"), enquiriesFile: join(directory, "enquiries.jsonl") });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  try {
    const bad = await fetch(`${base}/api/enquiries`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Sam" }) });
    assert.equal(bad.status, 400);
    const good = await fetch(`${base}/api/enquiries`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Sam", email: "sam@example.com", message: "A quote, please" }) });
    assert.equal(good.status, 201);
    assert.match(readFileSync(join(directory, "enquiries.jsonl"), "utf8"), /A quote, please/u);
    const home = await fetch(`${base}/`);
    assert.equal(home.status, 200);
    assert.match(home.headers.get("content-security-policy"), /script-src 'self'/u);
  } finally {
    await new Promise((resolve) => server.close(resolve));
    rmSync(directory, { recursive: true, force: true });
  }
});
