import { open, readFile } from "node:fs/promises";
import { basename, resolve } from "node:path";

/**
 * Recognises files a hand edit should not touch: lockfiles a package manager
 * writes, installed dependencies, vendored copies of other projects, and
 * generator output. A hand edit there is usually a mistake (a lockfile whose
 * integrity hashes no longer match, a generated file overwritten by the next
 * build), so the write tools refuse it once with the reason and the usual
 * remedy. The edit is not forbidden: the coder cannot run a package manager or
 * a generator, so an explicit `allowGenerated: true` still makes it.
 *
 * `.gitattributes` decides first, as it does for GitHub: `linguist-generated`
 * and `linguist-vendored` mark files, and `=false` / `-attr` clears the
 * defaults for files a repository maintains by hand.
 */

export type ProtectedFileKind = "lockfile" | "dependency" | "vendored" | "generated";

export interface ProtectedFile {
  readonly kind: ProtectedFileKind;
  /** One sentence the model can act on: what the file is and what to do instead. */
  readonly reason: string;
}

const LOCKFILES: Readonly<Record<string, string>> = {
  "package-lock.json": "npm install",
  "npm-shrinkwrap.json": "npm install",
  "yarn.lock": "yarn install",
  "pnpm-lock.yaml": "pnpm install",
  "bun.lock": "bun install",
  "bun.lockb": "bun install",
  "Cargo.lock": "cargo update",
  "poetry.lock": "poetry lock",
  "Pipfile.lock": "pipenv lock",
  "uv.lock": "uv lock",
  "composer.lock": "composer update",
  "Gemfile.lock": "bundle install",
  "go.sum": "go mod tidy",
  "packages.lock.json": "dotnet restore",
};

/** Directories a package manager installs into; never the repository's own source. */
const DEPENDENCY_DIRECTORIES = new Set(["node_modules", "bower_components", "jspm_packages", ".venv", "venv", "site-packages", ".yarn"]);
/** Directories that conventionally hold copies of other projects. */
const VENDORED_DIRECTORIES = new Set(["vendor", "third_party", "third-party", "thirdparty"]);

/** Markers generators write near the top of their output. */
const GENERATED_MARKERS = [/@generated\b/, /\bDO NOT EDIT\b/, /\bdo not edit\b.*\b(generated|auto-?generated)\b/i, /\b(auto-?generated|generated by)\b.*\bdo not (edit|modify)\b/i];
const MARKER_SCAN_LINES = 5;
const MARKER_SCAN_BYTES = 2_048;

export interface GeneratedFilePolicy {
  classify(relativePath: string): Promise<ProtectedFile | null>;
}

/** Reads `.gitattributes` once per repository; file markers are read per call. */
export async function loadGeneratedFilePolicy(root: string): Promise<GeneratedFilePolicy> {
  const attributes = parseGitattributes(await readText(resolve(root, ".gitattributes")));
  return {
    classify: async (relativePath) => classify(root, relativePath.replaceAll("\\", "/"), attributes),
  };
}

async function classify(root: string, path: string, attributes: readonly AttributeRule[]): Promise<ProtectedFile | null> {
  const generated = attributeValue(attributes, path, "linguist-generated");
  const vendored = attributeValue(attributes, path, "linguist-vendored");
  if (generated === true) return { kind: "generated", reason: `${path} is marked linguist-generated in .gitattributes: change what generates it instead.` };
  if (vendored === true) return { kind: "vendored", reason: `${path} is marked linguist-vendored in .gitattributes: it is a copy of another project, so change it upstream or patch it deliberately.` };

  const segments = path.split("/");
  const directories = segments.slice(0, -1);
  if (vendored !== false) {
    const dependency = directories.find((segment) => DEPENDENCY_DIRECTORIES.has(segment));
    if (dependency !== undefined) {
      return { kind: "dependency", reason: `${path} is inside ${dependency}/, installed by a package manager: edits there are not part of the repository and are lost on reinstall.` };
    }
    const vendor = directories.find((segment) => VENDORED_DIRECTORIES.has(segment));
    if (vendor !== undefined) {
      return { kind: "vendored", reason: `${path} is inside ${vendor}/, a vendored copy of another project: change it upstream, or patch it deliberately.` };
    }
  }
  if (generated === false) return null;

  const name = basename(path);
  const regenerate = LOCKFILES[name];
  if (regenerate !== undefined) {
    return { kind: "lockfile", reason: `${path} is a lockfile written by \`${regenerate}\`: change the manifest, and hand-edit the lockfile only if it must change in this same change and you keep it consistent.` };
  }
  const marker = await generatedMarker(resolve(root, path));
  if (marker !== null) return { kind: "generated", reason: `${path} says it is generated (${JSON.stringify(marker)}): change what generates it instead.` };
  return null;
}

async function generatedMarker(target: string): Promise<string | null> {
  let head: string;
  try {
    const handle = await open(target, "r");
    try {
      const buffer = Buffer.alloc(MARKER_SCAN_BYTES);
      const { bytesRead } = await handle.read(buffer, 0, MARKER_SCAN_BYTES, 0);
      head = buffer.subarray(0, bytesRead).toString("utf8");
    } finally {
      await handle.close();
    }
  } catch {
    return null; // A new file, or one the editor will reject for its own reasons.
  }
  for (const line of head.split(/\r?\n/).slice(0, MARKER_SCAN_LINES)) {
    if (GENERATED_MARKERS.some((pattern) => pattern.test(line))) return line.trim().slice(0, 120);
  }
  return null;
}

interface AttributeRule {
  readonly pattern: RegExp;
  readonly attributes: ReadonlyMap<string, boolean>;
}

/** The subset of gitattributes(5) that sets or unsets boolean attributes. */
export function parseGitattributes(text: string): AttributeRule[] {
  const rules: AttributeRule[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#") || line.startsWith("[attr]")) continue;
    const [pattern, ...fields] = line.split(/\s+/);
    if (pattern === undefined || pattern.startsWith("!")) continue;
    const attributes = new Map<string, boolean>();
    for (const field of fields) {
      if (field.startsWith("-") || field.startsWith("!")) attributes.set(field.slice(1), false);
      else if (field.endsWith("=false")) attributes.set(field.slice(0, -"=false".length), false);
      else if (field.endsWith("=true")) attributes.set(field.slice(0, -"=true".length), true);
      else if (!field.includes("=")) attributes.set(field, true);
    }
    if (attributes.size > 0) rules.push({ pattern: globToRegExp(pattern), attributes });
  }
  return rules;
}

/** Later lines win, as in git. undefined means no rule mentions the attribute. */
function attributeValue(rules: readonly AttributeRule[], path: string, attribute: string): boolean | undefined {
  let value: boolean | undefined;
  for (const rule of rules) {
    const setting = rule.attributes.get(attribute);
    if (setting !== undefined && rule.pattern.test(path)) value = setting;
  }
  return value;
}

/**
 * A pattern without a slash matches a name at any depth; with one, it is
 * anchored to the repository root. `**` crosses directories, `*` and `?` do
 * not. A pattern naming a directory (`dir/**`) covers everything below it.
 */
export function globToRegExp(pattern: string): RegExp {
  const anchored = pattern.replace(/\/$/, "").includes("/");
  const body = pattern.replace(/^\//, "").replace(/\/$/, "/**");
  let source = "";
  for (let index = 0; index < body.length; index += 1) {
    const character = body[index]!;
    if (character === "*" && body[index + 1] === "*") {
      const slashAfter = body[index + 2] === "/";
      source += slashAfter ? "(?:.*/)?" : ".*";
      index += slashAfter ? 2 : 1;
    } else if (character === "*") source += "[^/]*";
    else if (character === "?") source += "[^/]";
    else source += character.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  return new RegExp(anchored ? `^${source}$` : `(?:^|/)${source}$`);
}

async function readText(path: string): Promise<string> {
  try { return await readFile(path, "utf8"); } catch { return ""; }
}
