import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

// Generated by Atlas Genesis. Produces dist/: the server, its modules and the
// public files, after checking that every asset the page references exists
// and that the configuration is complete.

const root = process.cwd();
const dist = join(root, "dist");
const config = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8"));
const problems = [];
if (!config.name) problems.push("app.config.json has no name");
for (const entity of config.entities ?? []) {
  if (!entity.fields?.length) problems.push(`${entity.name} has no fields`);
  for (const field of entity.fields ?? []) if (field.type === "select" && !field.options?.length) problems.push(`${entity.name}.${field.key} has no options`);
}
if (existsSync(join(root, "public", "index.html"))) {
  const html = readFileSync(join(root, "public", "index.html"), "utf8");
  for (const [, ref] of html.matchAll(/(?:src|href)="\/([^"#?]+)"/gu)) if (!existsSync(join(root, "public", ref))) problems.push(`index.html references missing /${ref}`);
}
if (problems.length) { console.error(`Build failed:\n- ${problems.join("\n- ")}`); process.exit(1); }

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
for (const entry of ["server.mjs", "app.config.json", "package.json", "src", "public"]) if (existsSync(join(root, entry))) cpSync(join(root, entry), join(dist, entry), { recursive: true });
const hash = createHash("sha256");
for (const entry of ["server.mjs", "app.config.json"]) hash.update(readFileSync(join(root, entry)));
writeFileSync(join(dist, "build-info.json"), `${JSON.stringify({ name: config.name, builtAt: new Date().toISOString(), digest: hash.digest("hex").slice(0, 16) }, null, 2)}\n`);
console.log(`✓ Built ${config.name} into dist/`);
