import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { config, createApp } from "../server.mjs";
import { Auth } from "../src/auth.mjs";
import { FileStore } from "../src/files.mjs";
import { createScheduler } from "../src/jobs.mjs";
import { Secrets } from "../src/secrets.mjs";

// Generated by Atlas Genesis. Tests the backend building blocks this app
// uses: sign-in, file storage, secrets and scheduled jobs.

const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13]);

function scratch(t) {
  const dir = mkdtempSync(join(tmpdir(), "app-backend-"));
  t.after(() => rmSync(dir, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }));
  return dir;
}

async function withApp(t, run, options = {}) {
  const dir = scratch(t);
  const server = createApp({ dataFile: ":memory:", filesDir: join(dir, "files"), secretsFile: join(dir, "secrets.json"), env: {}, ...options });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  let cookie = "";
  const call = async (path, { method = "GET", body, headers = {} } = {}) => {
    const raw = Buffer.isBuffer(body);
    const response = await fetch(`${base}${path}`, {
      method,
      body: raw ? body : body === undefined ? undefined : JSON.stringify(body),
      headers: { ...(raw ? {} : { "content-type": "application/json" }), ...(cookie ? { cookie } : {}), ...headers },
    });
    const setCookie = response.headers.get("set-cookie");
    if (setCookie) cookie = setCookie.split(";")[0];
    const type = response.headers.get("content-type") ?? "";
    return { status: response.status, headers: response.headers, body: type.includes("json") ? await response.json() : Buffer.from(await response.arrayBuffer()) };
  };
  try { await run(call, dir); } finally { await new Promise((resolve) => server.close(resolve)); }
}

test("sign-in: the first account is the owner, sign-up then closes, and passwords are only stored hashed", async (t) => {
  const auth = new Auth();
  t.after(() => auth.close());
  assert.equal(auth.signupOpen(), true);
  const owner = await auth.createUser({ email: "Owner@Example.com", password: "correct horse" }, { role: "auto", signingUp: true });
  assert.equal(owner.role, "owner");
  assert.equal(owner.email, "owner@example.com");
  assert.equal(auth.signupOpen(), false);
  await assert.rejects(auth.createUser({ email: "second@example.com", password: "another pass" }, { role: "auto", signingUp: true }), (error) => error.status === 403);
  await assert.rejects(auth.createUser({ email: "owner@example.com", password: "whatever12" }), (error) => error.status === 409);
  await assert.rejects(auth.createUser({ email: "short@example.com", password: "short" }), (error) => error.status === 400);
  assert.equal(await auth.verify({ email: "owner@example.com", password: "wrong password" }), null);
  assert.equal((await auth.verify({ email: "OWNER@example.com", password: "correct horse" })).id, owner.id);
});

test("sign-in: people delete their own accounts, and the owner goes last", async (t) => {
  const auth = new Auth();
  t.after(() => auth.close());
  const owner = await auth.createUser({ email: "owner@example.com", password: "owner password" }, { role: "auto" });
  const member = await auth.createUser({ email: "member@example.com", password: "member password" }, { role: "auto" });
  assert.equal(member.role, "member");
  assert.throws(() => auth.deleteUser(owner.id), (error) => error.status === 409);
  const { token } = auth.startSession(member.id);
  assert.equal(auth.deleteUser(member.id), true);
  assert.equal(auth.userFrom({ headers: { cookie: `sid=${token}` } }), null, "their sessions end too");
  assert.equal(auth.deleteUser(owner.id), true);
  assert.equal(auth.signupOpen(), true, "with nobody left, the next person sets up the owner account");
});

test("sign-in: two people racing to sign up first cannot both become owners", async (t) => {
  const auth = new Auth();
  t.after(() => auth.close());
  const results = await Promise.allSettled([
    auth.createUser({ email: "a@example.com", password: "password-a" }, { role: "auto", signingUp: true }),
    auth.createUser({ email: "b@example.com", password: "password-b" }, { role: "auto", signingUp: true }),
  ]);
  assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
  assert.equal(auth.userCount(), 1);
});

test("sign-in: repeated wrong passwords are slowed down, and sessions expire", async (t) => {
  let now = Date.parse("2030-01-01T00:00:00Z");
  const auth = new Auth({ now: () => now });
  t.after(() => auth.close());
  const user = await auth.createUser({ email: "me@example.com", password: "right password" });
  for (let attempt = 0; attempt < 10; attempt += 1) assert.equal(await auth.verify({ email: "me@example.com", password: "nope nope" }), null);
  await assert.rejects(auth.verify({ email: "me@example.com", password: "right password" }), (error) => error.status === 429);
  now += 16 * 60 * 1000;
  assert.ok(await auth.verify({ email: "me@example.com", password: "right password" }), "the pause ends");
  const { token } = auth.startSession(user.id);
  const request = { headers: { cookie: `other=1; sid=${token}` } };
  assert.equal(auth.userFrom(request).id, user.id);
  assert.equal(auth.userFrom({ headers: { authorization: `Bearer ${token}` } }), null, "bearer tokens only when enabled");
  now += 15 * 24 * 60 * 60 * 1000;
  assert.equal(auth.userFrom(request), null, "expired");
  auth.startSession(user.id);
  now += 15 * 24 * 60 * 60 * 1000;
  assert.equal(auth.purgeExpired(), 1);
});

test("the API signs people in and out, and refuses cross-site writes", (t) => withApp(t, async (call) => {
  assert.deepEqual((await call("/api/auth/me")).body, { user: null, signupOpen: true });
  const signup = await call("/api/auth/signup", { method: "POST", body: { email: "owner@example.com", password: "owner password" } });
  assert.equal(signup.status, 201, JSON.stringify(signup.body));
  assert.match(signup.headers.get("set-cookie"), /HttpOnly; SameSite=Lax/u);
  assert.equal((await call("/api/auth/me")).body.user.role, "owner");
  const closed = await call("/api/auth/signup", { method: "POST", body: { email: "x@example.com", password: "x password" } });
  assert.equal(closed.status, 403);
  const added = await call("/api/auth/users", { method: "POST", body: { email: "team@example.com", password: "team password" } });
  assert.equal(added.status, 201);
  assert.equal((await call("/api/secrets")).status, 200, "the owner sees the secrets status");
  const crossSite = await call("/api/auth/logout", { method: "POST", headers: { origin: "https://evil.example" } });
  assert.equal(crossSite.status, 403);
  assert.equal((await call("/api/auth/logout", { method: "POST" })).status, 200);
  assert.equal((await call("/api/auth/me")).body.user, null);
  const login = await call("/api/auth/login", { method: "POST", body: { email: "team@example.com", password: "team password" } });
  assert.equal(login.status, 200);
  assert.equal(login.body.user.role, "member");
  assert.equal((await call("/api/auth/users", { method: "POST", body: { email: "y@example.com", password: "y password" } })).status, 403, "only the owner adds accounts");
  if (config.auth?.required) {
    assert.equal((await call("/api/secrets")).status, 403, "members cannot see owner tools");
    await call("/api/auth/logout", { method: "POST" });
    const entity = config.entities.find((candidate) => !config.booking || candidate.slug !== config.booking.entity) ?? config.entities[0];
    assert.equal((await call(`/api/${entity.slug}`)).status, 401, "private data needs sign-in");
    assert.equal((await call("/api/files")).status, 401);
    assert.equal((await call("/api/health")).status, 200, "health stays public");
  }
}));

test("files: checked types, size limit, safe downloads", (t) => withApp(t, async (call, dir) => {
  if (config.auth?.required) await call("/api/auth/signup", { method: "POST", body: { email: "owner@example.com", password: "owner password" } });
  const upload = await call("/api/files", { method: "POST", body: PNG, headers: { "content-type": "image/png", "x-file-name": encodeURIComponent("../../photo.png") } });
  assert.equal(upload.status, 201, JSON.stringify(upload.body));
  assert.equal(upload.body.file.name, "photo.png", "a name cannot carry a path");
  const fake = await call("/api/files", { method: "POST", body: Buffer.from("<script>alert(1)</script>"), headers: { "content-type": "image/png" } });
  assert.equal(fake.status, 415, "contents must match the type");
  const html = await call("/api/files", { method: "POST", body: Buffer.from("<html></html>"), headers: { "content-type": "text/html" } });
  assert.equal(html.status, 415, "HTML is never accepted");
  const text = await call("/api/files", { method: "POST", body: Buffer.from("hello"), headers: { "content-type": "text/plain", "x-file-name": "notes.txt" } });
  const download = await call(`/api/files/${text.body.file.id}`);
  assert.equal(download.body.toString(), "hello");
  assert.match(download.headers.get("content-disposition"), /^attachment/u);
  assert.match(download.headers.get("content-security-policy"), /sandbox/u);
  assert.equal(download.headers.get("x-content-type-options"), "nosniff");
  assert.match((await call(`/api/files/${upload.body.file.id}`)).headers.get("content-disposition"), /^inline/u);
  assert.equal((await call("/api/files")).body.files.length, 2);
  assert.equal((await call(`/api/files/${upload.body.file.id}`, { method: "DELETE" })).status, 200);
  assert.equal((await call(`/api/files/${upload.body.file.id}`)).status, 404);
  assert.equal((await call("/api/files/..%2F..%2Fsecrets.json")).status, 404);

  const small = new FileStore({ dir: join(dir, "small"), maxBytes: 4 });
  t.after(() => small.close());
  assert.throws(() => small.save({ name: "big.txt", type: "text/plain", data: Buffer.from("too big") }), (error) => error.status === 413);
}));

test("secrets: environment wins, the file is private, and no route returns a value", (t) => withApp(t, async (call, dir) => {
  const file = join(dir, "secrets.json");
  const secrets = new Secrets({ file, declared: ["PAYMENTS_SECRET_KEY", "EMAIL_API_KEY"], env: { EMAIL_API_KEY: "from-env" } });
  assert.throws(() => secrets.get("PAYMENTS_SECRET_KEY"), /not set/u);
  secrets.set("PAYMENTS_SECRET_KEY", "sk_test_value\n");
  assert.equal(secrets.get("PAYMENTS_SECRET_KEY"), "sk_test_value");
  secrets.set("EMAIL_API_KEY", "from-file");
  assert.equal(secrets.get("EMAIL_API_KEY"), "from-env", "the environment wins over the file");
  if (process.platform !== "win32") assert.equal(statSync(file).mode & 0o777, 0o600);
  assert.deepEqual(secrets.status().map((entry) => [entry.name, entry.configured, entry.source]), [["EMAIL_API_KEY", true, "environment"], ["PAYMENTS_SECRET_KEY", true, "file"]]);
  assert.doesNotMatch(JSON.stringify(secrets.status()), /sk_test_value|from-env|from-file/u);
  assert.throws(() => secrets.set("lower", "x"), /not a valid secret name/u);
  if (config.auth?.required) await call("/api/auth/signup", { method: "POST", body: { email: "owner@example.com", password: "owner password" } });
  const listed = await call("/api/secrets");
  assert.equal(listed.status, 200);
  assert.doesNotMatch(JSON.stringify(listed.body), /sk_test_value/u);
  assert.doesNotMatch(JSON.stringify((await call("/api/config")).body), /sk_test_value/u);
  assert.ok(readFileSync(file, "utf8").includes("sk_test_value"));
}));

test("jobs: run on their cron schedule, never overlap, and record failures", async () => {
  let now = new Date(2030, 0, 1, 8, 59, 30);
  const timers = [];
  let calls = 0;
  let release;
  const scheduler = createScheduler({
    schedule: [{ name: "report", schedule: "0 9 * * *" }, { name: "broken", schedule: "*/5 * * * *" }],
    jobs: {
      report: () => { calls += 1; return new Promise((resolve) => { release = resolve; }); },
      broken: () => { throw new Error("no connection"); },
    },
    now: () => now,
    setTimer: (fn, ms) => { const timer = { fn, ms }; timers.push(timer); return timer; },
    clearTimer: (timer) => { timers.splice(timers.indexOf(timer), 1); },
    log: {},
  });
  assert.throws(() => createScheduler({ schedule: [{ name: "missing", schedule: "* * * * *" }] }), /not defined/u);
  scheduler.start();
  assert.equal(timers.length, 2);
  assert.equal(timers[0].ms, 30_000, "waits until 9:00");
  assert.equal(scheduler.status()[0].nextAt, new Date(2030, 0, 1, 9, 0).toISOString());
  now = new Date(2030, 0, 1, 9, 0, 0);
  const firing = timers.shift().fn();
  assert.equal(calls, 1);
  assert.equal((await scheduler.runNow("report")).status, "skipped", "never runs twice at once");
  release("done");
  await firing;
  assert.equal(scheduler.status()[0].lastRun.status, "succeeded");
  assert.equal((await scheduler.runNow("broken")).error, "no connection");
  await assert.rejects(scheduler.runNow("nope"), (error) => error.status === 404);
  scheduler.stop();
  assert.equal(timers.length, 0);
});
